// ============================================================
//  DATA LAYER — explorequangtri.com
//  Tất cả dữ liệu địa điểm, dịch vụ, lộ trình, tips
// ============================================================

const CATEGORIES = {
  history:   { label: 'Di tích Lịch sử', icon: '🏛️', color: '#c0392b' },
  nature:    { label: 'Danh lam Thắng cảnh', icon: '🌿', color: '#27ae60' },
  beach:     { label: 'Biển & Đảo', icon: '🏖️', color: '#2980b9' },
  religion:  { label: 'Tâm linh & Tín ngưỡng', icon: '⛩️', color: '#8e44ad' },
  food:      { label: 'Ẩm thực', icon: '🍜', color: '#e67e22' },
  stay:      { label: 'Lưu trú', icon: '🏨', color: '#16a085' },
  transport: { label: 'Dịch vụ Vận chuyển', icon: '🚗', color: '#7f8c8d' },
  service:   { label: 'Dịch vụ Tiện ích', icon: '🏪', color: '#2c3e50' },
};

// ============================================================
//  DESTINATIONS — địa điểm du lịch
// ============================================================
const destinations = [
  // ── LỊCH SỬ ──────────────────────────────────────────────
  {
    id: 1,
    name: 'Thành Cổ Quảng Trị',
    nameEn: 'Quảng Trị Ancient Citadel',
    category: 'history',
    subcategory: 'Thành cổ & Chiến tích',
    lat: 16.7416,
    lng: 107.1891,
    address: 'Thị xã Quảng Trị, tỉnh Quảng Trị',
    description: `Thành Cổ Quảng Trị là chứng tích bi hùng của cuộc chiến 81 ngày đêm mùa hè năm 1972. Được xây dựng từ thời Nguyễn (thế kỷ XIX), pháo đài này đã trở thành biểu tượng của sự hy sinh anh dũng khi hàng nghìn chiến sĩ ngã xuống để bảo vệ từng tấc đất. Ngày nay là công viên tưởng niệm với tượng đài, đài tưởng niệm và hồ sen bao quanh thành.`,
    hours: '06:00 – 18:00 (hàng ngày)',
    admission: 'Miễn phí',
    phone: '0233 3852 797',
    website: '',
    rating: 4.9,
    reviews: 3254,
    duration: '1–2 giờ',
    bestTime: 'Sáng sớm (6–8h) hoặc chiều mát (16–18h) — tránh nắng trưa',
    highlight: true,
    tags: ['lịch sử', 'chiến tranh', 'di tích quốc gia', 'tưởng niệm'],
    tips: [
      'Mặc trang phục kín đáo, lịch sự để thể hiện sự tôn trọng',
      'Thuê hướng dẫn viên tại chỗ để nghe câu chuyện lịch sử sinh động',
      'Ghé thăm buổi chiều tà — ánh sáng đẹp và mát mẻ hơn',
      'Đọc bia ghi chép lịch sử xung quanh tường thành để hiểu sâu hơn',
    ],
    nearbyFood: ['Quán cơm Mẹ Đất', 'Bánh mì Phượng Hải'],
    nearbyStay: ['Khách sạn Cố Đô', 'Nhà nghỉ Thành Cổ'],
    images: ['thanh-co-1.jpg', 'thanh-co-2.jpg', 'thanh-co-3.jpg'],
  },
  {
    id: 2,
    name: 'Cầu Hiền Lương – Sông Bến Hải',
    nameEn: 'Hien Luong Bridge – Ben Hai River',
    category: 'history',
    subcategory: 'Di tích phân chia đất nước',
    lat: 17.0558,
    lng: 107.0783,
    address: 'Xã Vĩnh Thành, huyện Vĩnh Linh, Quảng Trị',
    description: `Cầu Hiền Lương bắc qua sông Bến Hải từng là ranh giới chia cắt hai miền Nam – Bắc Việt Nam (1954–1975) theo Hiệp định Genève. Màu xanh và vàng hai bên cầu, hai chiếc loa phát thanh đối diện nhau là hình ảnh đau thương một thời lịch sử. Nay là di tích quốc gia đặc biệt, nơi tưởng niệm khát vọng thống nhất của dân tộc.`,
    hours: '07:00 – 17:30 (hàng ngày)',
    admission: 'Miễn phí',
    phone: '0233 3671 012',
    website: '',
    rating: 4.8,
    reviews: 2187,
    duration: '1–1.5 giờ',
    bestTime: 'Sáng sớm — ánh sáng đẹp, ít khách',
    highlight: true,
    tags: ['lịch sử', 'phân chia', 'bến hải', 'di tích đặc biệt'],
    tips: [
      'Tham quan bảo tàng nhỏ bên cầu để hiểu đầy đủ lịch sử',
      'Kết hợp tham quan Đôi bờ Hiền Lương (bên bắc và bên nam)',
      'Chụp ảnh tốt nhất vào sáng sớm hoặc lúc hoàng hôn',
    ],
    nearbyFood: ['Quán ăn Bến Hải', 'Nhà hàng Hương Đồng'],
    nearbyStay: ['Nhà nghỉ Vĩnh Linh', 'Khách sạn Sông Bến Hải'],
    images: ['cau-hien-luong-1.jpg', 'cau-hien-luong-2.jpg'],
  },
  {
    id: 3,
    name: 'Địa đạo Vịnh Mốc',
    nameEn: 'Vinh Moc Tunnels',
    category: 'history',
    subcategory: 'Địa đạo chiến tranh',
    lat: 17.0851,
    lng: 107.0614,
    address: 'Xã Vĩnh Thạch, huyện Vĩnh Linh, Quảng Trị',
    description: `Địa đạo Vịnh Mốc là hệ thống đường hầm dài hơn 2 km nằm sâu dưới lòng đất, được người dân đào tay trong những năm 1966–1967 để tránh bom đạn Mỹ. Hơn 60 gia đình với khoảng 300 người đã sống dưới lòng đất suốt nhiều năm liền, 17 đứa trẻ được sinh ra trong lòng đất này. Đây là biểu tượng của ý chí kiên cường và tinh thần bất khuất của người dân Quảng Trị.`,
    hours: '07:00 – 17:00 (hàng ngày)',
    admission: '40.000 VNĐ/người',
    phone: '0233 3850 055',
    website: '',
    rating: 4.7,
    reviews: 1876,
    duration: '1.5–2 giờ',
    bestTime: 'Sáng (7–11h) — trời mát hơn khi đi bộ ngoài trời',
    highlight: true,
    tags: ['địa đạo', 'chiến tranh', 'lịch sử', 'VN nổi tiếng'],
    tips: [
      'Mặc quần áo thoải mái, giày đế bằng — đường trong hầm hẹp và thấp',
      'Mang đèn pin dự phòng dù có đèn trong hầm',
      'Chiều cao trung bình hầm ~1.5m — người cao chú ý cúi người',
      'Thời gian đi hết cả hệ thống khoảng 45 phút',
      'Hướng dẫn viên tại đây rất nhiệt tình và am hiểu lịch sử',
    ],
    nearbyFood: ['Quán Cô Ba - Hải sản Vịnh Mốc', 'Nhà hàng Cửa Tùng'],
    nearbyStay: ['Khu nghỉ dưỡng Cửa Tùng', 'Nhà nghỉ Vịnh Mốc'],
    images: ['vinh-moc-1.jpg', 'vinh-moc-2.jpg', 'vinh-moc-3.jpg'],
  },
  {
    id: 4,
    name: 'Nghĩa trang Liệt sĩ Quốc gia Trường Sơn',
    nameEn: 'Truong Son National Cemetery',
    category: 'history',
    subcategory: 'Nghĩa trang liệt sĩ',
    lat: 16.9583,
    lng: 106.9067,
    address: 'Huyện Gio Linh, tỉnh Quảng Trị',
    description: `Nghĩa trang lớn nhất Việt Nam với hơn 10.000 phần mộ của các liệt sĩ hy sinh trên đường Trường Sơn – Đường Hồ Chí Minh huyền thoại. Kiến trúc nghĩa trang uy nghi trên triền đồi, với tháp chuông đồng hồ cao 12m và khu trưng bày lịch sử. Đây là nơi hành hương tâm linh của hàng triệu người Việt.`,
    hours: '07:00 – 17:30 (hàng ngày)',
    admission: 'Miễn phí',
    phone: '0233 3870 119',
    website: '',
    rating: 4.9,
    reviews: 2654,
    duration: '1–2 giờ',
    bestTime: 'Sáng sớm — không khí trang nghiêm và mát mẻ',
    highlight: false,
    tags: ['nghĩa trang', 'liệt sĩ', 'trường sơn', 'tâm linh'],
    tips: [
      'Ăn mặc trang trọng, không mặc đồ sặc sỡ',
      'Nói chuyện nhẹ nhàng, tránh gây ồn ào',
      'Có thể thắp nhang tưởng niệm tại cổng',
      'Kết hợp với thăm Nghĩa trang Đường 9 cùng ngày (cách 40km)',
    ],
    nearbyFood: ['Quán cơm Trường Sơn', 'Nhà hàng đường 9'],
    nearbyStay: ['Nhà nghỉ Gio Linh'],
    images: ['truong-son-1.jpg', 'truong-son-2.jpg'],
  },
  {
    id: 5,
    name: 'Nghĩa trang Liệt sĩ Đường 9',
    nameEn: 'Route 9 National Cemetery',
    category: 'history',
    subcategory: 'Nghĩa trang liệt sĩ',
    lat: 16.7506,
    lng: 106.9589,
    address: 'Phường 4, thành phố Đông Hà, Quảng Trị',
    description: `Nghĩa trang liệt sĩ Quốc gia Đường 9 nằm trên đồi thông cao, là nơi an nghỉ của hàng nghìn chiến sĩ hy sinh trên chiến trường Đường 9 – Khe Sanh. Khu tưởng niệm uy nghi với tượng đài Chiến thắng Đường 9 – Khe Sanh, vườn cây xanh mát và không gian tâm linh trang nghiêm.`,
    hours: '07:00 – 17:30 (hàng ngày)',
    admission: 'Miễn phí',
    phone: '0233 3559 111',
    website: '',
    rating: 4.8,
    reviews: 1432,
    duration: '45 phút – 1.5 giờ',
    bestTime: 'Sáng sớm',
    highlight: false,
    tags: ['nghĩa trang', 'đường 9', 'khe sanh', 'liệt sĩ'],
    tips: [
      'Kết hợp tham quan Bảo tàng Đường 9 gần đó',
      'Không thích hợp cho trẻ em dưới 5 tuổi',
    ],
    nearbyFood: ['Nhà hàng Đông Hà Plaza'],
    nearbyStay: ['Khách sạn Sài Gòn Đông Hà'],
    images: ['duong-9-cemetery-1.jpg'],
  },
  {
    id: 6,
    name: 'Căn cứ Khe Sanh',
    nameEn: 'Khe Sanh Combat Base',
    category: 'history',
    subcategory: 'Căn cứ quân sự',
    lat: 16.6183,
    lng: 106.7422,
    address: 'Thị trấn Khe Sanh, huyện Hướng Hóa, Quảng Trị',
    description: `Căn cứ Khe Sanh từng là trận địa quyết liệt nhất trong Chiến tranh Việt Nam (1968), nơi diễn ra trận bao vây kéo dài 77 ngày. Ngày nay là bảo tàng ngoài trời với máy bay, xe tăng, trực thăng và các chiến hào còn giữ lại. Nằm ở huyện Hướng Hóa, sát biên giới Lào, giữa vùng núi hùng vĩ của Trường Sơn.`,
    hours: '07:00 – 17:00 (hàng ngày)',
    admission: '20.000 VNĐ/người',
    phone: '0233 3876 001',
    website: '',
    rating: 4.6,
    reviews: 987,
    duration: '1–2 giờ',
    bestTime: 'Sáng (tránh nóng buổi chiều ở cao nguyên)',
    highlight: false,
    tags: ['chiến tranh', 'khe sanh', 'căn cứ', 'bảo tàng ngoài trời'],
    tips: [
      'Thuê xe máy từ Đông Hà hoặc Đà Lạt đến Khe Sanh (170km, 3h)',
      'Kết hợp tham quan vùng núi Hướng Hóa và cà phê Khe Sanh',
      'Cà phê Khe Sanh nổi tiếng — mua làm quà tặng',
      'Đường đến Khe Sanh có cảnh đẹp núi rừng Trường Sơn',
    ],
    nearbyFood: ['Quán phở Khe Sanh', 'Nhà hàng Hướng Hóa'],
    nearbyStay: ['Nhà nghỉ Khe Sanh', 'Homestay bản Khe Sanh'],
    images: ['khe-sanh-1.jpg', 'khe-sanh-2.jpg'],
  },

  // ── THIÊN NHIÊN & THẮNG CẢNH ─────────────────────────────
  {
    id: 7,
    name: 'Thác Tà Puồng',
    nameEn: 'Ta Puong Waterfall',
    category: 'nature',
    subcategory: 'Thác nước',
    lat: 16.5841,
    lng: 106.6234,
    address: 'Xã Hướng Phùng, huyện Hướng Hóa, Quảng Trị',
    description: `Thác Tà Puồng là một trong những thác nước đẹp và hùng vĩ nhất tỉnh Quảng Trị. Nằm sâu trong rừng nguyên sinh Trường Sơn, thác có độ cao khoảng 80m đổ xuống những tầng đá rêu phong cổ kính. Đường đến thác đi qua những bản làng dân tộc Pa Kô, Vân Kiều thơ mộng.`,
    hours: 'Mở cửa tự do',
    admission: 'Miễn phí',
    phone: '',
    website: '',
    rating: 4.5,
    reviews: 543,
    duration: '2–4 giờ (bao gồm đi bộ)',
    bestTime: 'Tháng 9–11 (mùa nước lớn)',
    highlight: false,
    tags: ['thác nước', 'thiên nhiên', 'trekking', 'rừng nguyên sinh'],
    tips: [
      'Cần đi với người địa phương hoặc hướng dẫn viên am hiểu đường',
      'Đường đến thác khoảng 3km đi bộ qua rừng',
      'Mặc quần áo gọn nhẹ, mang giày leo núi',
      'Mang nước uống đủ và đồ ăn nhẹ',
      'Tránh đi mùa mưa lớn — đường trơn nguy hiểm',
    ],
    nearbyFood: ['Nhà hàng bản Khe Sanh'],
    nearbyStay: ['Homestay bản người Vân Kiều'],
    images: ['ta-puong-1.jpg', 'ta-puong-2.jpg'],
  },
  {
    id: 8,
    name: 'Rừng Nguyên sinh Đakrông',
    nameEn: 'Dakrong Nature Reserve',
    category: 'nature',
    subcategory: 'Rừng nguyên sinh & Bảo tồn',
    lat: 16.6019,
    lng: 106.8806,
    address: 'Huyện Đakrông, tỉnh Quảng Trị',
    description: `Khu Bảo tồn thiên nhiên Đakrông với diện tích hơn 37.000 ha là nơi sinh sống của nhiều loài động thực vật quý hiếm, trong đó có loài Sao la — loài thú có vú cực kỳ nguy cấp. Dòng sông Đakrông xanh trong chảy qua những bản làng Pa Kô, Vân Kiều tạo nên cảnh quan hữu tình. Cầu treo Đakrông là điểm check-in nổi tiếng.`,
    hours: 'Mở cửa tự do',
    admission: 'Miễn phí (khu rừng bảo tồn cần xin phép)',
    phone: '0233 3877 105',
    website: '',
    rating: 4.4,
    reviews: 432,
    duration: 'Nửa ngày đến cả ngày',
    bestTime: 'Tháng 3–5 và Tháng 9–11',
    highlight: false,
    tags: ['rừng nguyên sinh', 'bảo tồn', 'thiên nhiên', 'trekking', 'văn hóa dân tộc'],
    tips: [
      'Liên hệ Ban quản lý khu bảo tồn trước để được hướng dẫn',
      'Có thể thuê xe máy từ Đông Hà, đường Quốc lộ 9 đẹp',
      'Ghé thăm các bản làng dân tộc Pa Kô, Vân Kiều dọc đường',
      'Mang kem chống côn trùng',
    ],
    nearbyFood: ['Nhà hàng dọc quốc lộ 9'],
    nearbyStay: ['Homestay Đakrông', 'Nhà nghỉ Hướng Hóa'],
    images: ['dakrong-1.jpg', 'dakrong-2.jpg'],
  },
  {
    id: 9,
    name: 'Suối nước nóng Đakrông',
    nameEn: 'Dakrong Hot Springs',
    category: 'nature',
    subcategory: 'Suối nước nóng',
    lat: 16.6241,
    lng: 106.9033,
    address: 'Xã Đakrông, huyện Đakrông, Quảng Trị',
    description: `Suối nước nóng Đakrông với nhiệt độ 40–60°C nằm cạnh dòng sông Đakrông trong xanh. Hệ thống bể tắm khoáng thiên nhiên được xây dựng trong khung cảnh rừng núi yên bình, thích hợp để thư giãn và trị liệu. Đặc biệt phù hợp cho những ai mắc các bệnh về xương khớp, da liễu.`,
    hours: '07:00 – 21:00',
    admission: '30.000–80.000 VNĐ/người',
    phone: '0233 3877 456',
    website: '',
    rating: 4.3,
    reviews: 328,
    duration: '1–3 giờ',
    bestTime: 'Tháng 10–3 (trời mát, ngâm suối càng thích)',
    highlight: false,
    tags: ['suối nước nóng', 'nghỉ dưỡng', 'trị liệu', 'thiên nhiên'],
    tips: [
      'Mang đồ bơi theo',
      'Nước ở bể nóng nhất có thể gây bỏng — thử từ từ',
      'Kết hợp tham quan cầu treo Đakrông và làng dân tộc',
    ],
    nearbyFood: ['Quán ăn dân tộc Đakrông'],
    nearbyStay: ['Khu nghỉ dưỡng Đakrông'],
    images: ['suoi-nuoc-nong-1.jpg'],
  },

  // ── BIỂN & ĐẢO ────────────────────────────────────────────
  {
    id: 10,
    name: 'Biển Cửa Tùng',
    nameEn: 'Cua Tung Beach',
    category: 'beach',
    subcategory: 'Bãi biển',
    lat: 17.0281,
    lng: 107.1017,
    address: 'Xã Vĩnh Quang, huyện Vĩnh Linh, Quảng Trị',
    description: `Biển Cửa Tùng được mệnh danh là "Nữ hoàng của các bãi biển" với bờ cát trắng mịn uốn lượn, nước biển trong xanh và những rặng phi lao vi vu. Nằm ở cửa sông Bến Hải, bãi biển có chiều dài hơn 3km với làn nước trong vắt. Từng là điểm nghỉ mát yêu thích của hoàng gia triều Nguyễn và quan chức thực dân Pháp.`,
    hours: 'Mở cửa tự do (24/7)',
    admission: 'Miễn phí',
    phone: '',
    website: '',
    rating: 4.6,
    reviews: 1543,
    duration: 'Nửa ngày đến cả ngày',
    bestTime: 'Tháng 5–8 (thời tiết nóng, biển đẹp)',
    highlight: true,
    tags: ['biển', 'bơi lội', 'nghỉ mát', 'cửa tùng'],
    tips: [
      'Buổi sáng sớm (trước 8h) nước biển trong nhất và ít người',
      'Tránh biển vào buổi trưa — nắng gắt, tia UV cao',
      'Có thể thuê thuyền đánh cá đi câu buổi sớm',
      'Hải sản tươi ngon tại các nhà hàng ven biển',
      'Gần Địa đạo Vịnh Mốc và Cầu Hiền Lương — kết hợp tham quan 1 ngày',
    ],
    nearbyFood: ['Nhà hàng hải sản Cửa Tùng', 'Quán Cô Liên', 'Chợ cá Cửa Tùng'],
    nearbyStay: ['Resort Cửa Tùng', 'Nhà nghỉ Bình Minh', 'Homestay biển'],
    images: ['cua-tung-1.jpg', 'cua-tung-2.jpg', 'cua-tung-3.jpg'],
  },
  {
    id: 11,
    name: 'Biển Cửa Việt',
    nameEn: 'Cua Viet Beach',
    category: 'beach',
    subcategory: 'Bãi biển',
    lat: 16.9297,
    lng: 107.1544,
    address: 'Thị trấn Cửa Việt, huyện Gio Linh, Quảng Trị',
    description: `Cửa Việt là bãi biển sầm uất nhất Quảng Trị với bờ cát dài, cảng cá lớn và nhiều nhà hàng hải sản tươi ngon. Cửa Việt nổi tiếng với hải sản phong phú: tôm, cua, mực, cá tươi sống. Biển có sóng vừa phải, thích hợp tắm biển và chơi thể thao nước.`,
    hours: 'Mở cửa tự do',
    admission: 'Miễn phí',
    phone: '',
    website: '',
    rating: 4.4,
    reviews: 1876,
    duration: 'Nửa ngày đến cả ngày',
    bestTime: 'Tháng 5–8',
    highlight: false,
    tags: ['biển', 'hải sản', 'cảng cá', 'tắm biển'],
    tips: [
      'Mua hải sản trực tiếp từ thuyền buổi sáng sớm (5–7h) — tươi và rẻ nhất',
      'Khu chợ đêm hải sản Cửa Việt rất nhộn nhịp',
      'Thích hợp câu cá từ bờ vào buổi chiều',
    ],
    nearbyFood: ['Nhà hàng Biển Đông', 'Quán Cô Năm Hải Sản', 'Chợ đêm Cửa Việt'],
    nearbyStay: ['Khách sạn biển Cửa Việt', 'Nhà nghỉ Hương Giang'],
    images: ['cua-viet-1.jpg', 'cua-viet-2.jpg'],
  },
  {
    id: 12,
    name: 'Đảo Cồn Cỏ',
    nameEn: 'Con Co Island',
    category: 'beach',
    subcategory: 'Đảo',
    lat: 17.1719,
    lng: 107.3439,
    address: 'Huyện đảo Cồn Cỏ, tỉnh Quảng Trị',
    description: `Cồn Cỏ là huyện đảo nhỏ nằm cách bờ biển Cửa Việt khoảng 28km. Được bao phủ bởi rừng nguyên sinh nhiệt đới, bãi đá ngầm san hô còn nguyên sơ và làn nước biển trong vắt màu ngọc lam. Đây là thiên đường lặn biển (snorkeling/diving) với đa dạng san hô và cá biển nhiều màu sắc. Đảo còn lưu giữ nhiều di tích lịch sử từ thời chiến tranh.`,
    hours: 'Tàu từ Cửa Việt 7:00 và 13:00',
    admission: 'Vé tàu: 150.000 VNĐ/chiều',
    phone: '0233 3568 123',
    website: '',
    rating: 4.7,
    reviews: 765,
    duration: '1–2 ngày',
    bestTime: 'Tháng 3–8 (biển lặng, nước trong)',
    highlight: true,
    tags: ['đảo', 'lặn biển', 'san hô', 'thiên nhiên', 'hoang sơ'],
    tips: [
      'Đặt tàu trước vào mùa hè (tháng 6–8) — rất đông khách',
      'Mang theo đồ lặn (snorkel, kính) hoặc thuê tại đảo',
      'Mùa đông (tháng 11–2) biển động — không nên đi',
      'Lưu trú tại đảo 1 đêm để trải nghiệm hoàng hôn và bình minh biển',
      'Mang đủ tiền mặt — đảo không có ATM',
    ],
    nearbyFood: ['Nhà hàng hải sản đảo Cồn Cỏ', 'Canteen huyện đảo'],
    nearbyStay: ['Nhà khách huyện đảo Cồn Cỏ', 'Homestay đảo'],
    images: ['con-co-1.jpg', 'con-co-2.jpg', 'con-co-3.jpg'],
  },

  // ── TÂM LINH & TÍN NGƯỠNG ───────────────────────────────
  {
    id: 13,
    name: 'Linh địa Đức Mẹ La Vang',
    nameEn: 'La Vang Marian Shrine',
    category: 'religion',
    subcategory: 'Linh địa Công giáo',
    lat: 16.7483,
    lng: 107.1203,
    address: 'Xã Hải Phú, huyện Hải Lăng, Quảng Trị',
    description: `Linh địa La Vang là một trong những nơi hành hương Công giáo linh thiêng và nổi tiếng nhất Đông Nam Á. Tương truyền Đức Mẹ Maria đã hiện ra tại đây năm 1798 để an ủi và chữa lành cho giáo dân đang bị bách hại. Đại hội hành hương La Vang tổ chức 3 năm một lần (tháng 8), thu hút hàng trăm nghìn tín hữu. Công trình Vương cung Thánh đường La Vang đang được xây dựng quy mô lớn.`,
    hours: '06:00 – 20:00 (hàng ngày)',
    admission: 'Miễn phí',
    phone: '0233 3852 112',
    website: 'lavang.vn',
    rating: 4.9,
    reviews: 4321,
    duration: '1–3 giờ',
    bestTime: 'Sáng sớm hoặc chiều tối (tránh nắng) | Tránh dịp lễ lớn nếu không muốn đông người',
    highlight: true,
    tags: ['tâm linh', 'công giáo', 'la vang', 'hành hương', 'đức mẹ'],
    tips: [
      'Mặc trang phục lịch sự, kín đáo khi vào khu thánh địa',
      'Nếu đến dịp Đại hội (tháng 8 năm lẻ) phải đặt phòng trước rất sớm',
      'Đừng quên thắp nến và cầu nguyện tại hang đá Đức Mẹ',
      'Mua quà lưu niệm tôn giáo tại các cửa hàng quanh khu hành hương',
    ],
    nearbyFood: ['Quán chay La Vang', 'Nhà hàng Mẹ Đất'],
    nearbyStay: ['Nhà khách La Vang', 'Khách sạn Đức Mẹ', 'Nhà thờ cung cấp phòng nghỉ'],
    images: ['la-vang-1.jpg', 'la-vang-2.jpg', 'la-vang-3.jpg'],
  },
  {
    id: 14,
    name: 'Chùa Sắc Tứ Tịnh Quang',
    nameEn: 'Sac Tu Tinh Quang Pagoda',
    category: 'religion',
    subcategory: 'Chùa Phật giáo',
    lat: 16.8167,
    lng: 107.1003,
    address: 'Thành phố Đông Hà, tỉnh Quảng Trị',
    description: `Chùa Sắc Tứ Tịnh Quang là ngôi chùa cổ kính và linh thiêng nhất tỉnh Quảng Trị. Được xây dựng từ thế kỷ XVII thời chúa Nguyễn, chùa lưu giữ nhiều hiện vật cổ quý giá và kiến trúc truyền thống. Khuôn viên chùa rộng rãi với vườn cây xanh mát, hồ sen, tượng Phật lớn.`,
    hours: '06:00 – 18:00 (hàng ngày)',
    admission: 'Miễn phí',
    phone: '0233 3553 321',
    website: '',
    rating: 4.5,
    reviews: 876,
    duration: '30–60 phút',
    bestTime: 'Sáng sớm — không khí tĩnh lặng, chuông ngân',
    highlight: false,
    tags: ['chùa', 'phật giáo', 'tâm linh', 'cổ kính'],
    tips: [
      'Ăn mặc kín đáo, tháo giày trước khi vào chánh điện',
      'Có thể dùng bữa cơm chay tại chùa vào ngày rằm và mùng 1',
    ],
    nearbyFood: ['Cơm chay tại chùa', 'Quán ăn Đông Hà'],
    nearbyStay: ['Khách sạn Đông Hà'],
    images: ['chua-tinh-quang-1.jpg'],
  },

  // ── THÀNH PHỐ ĐÔNG HÀ ────────────────────────────────────
  {
    id: 15,
    name: 'Bảo tàng tỉnh Quảng Trị',
    nameEn: 'Quang Tri Provincial Museum',
    category: 'history',
    subcategory: 'Bảo tàng',
    lat: 16.8461,
    lng: 107.1012,
    address: 'Đường Hùng Vương, TP. Đông Hà, tỉnh Quảng Trị',
    description: `Bảo tàng tỉnh Quảng Trị lưu giữ và trưng bày hơn 20.000 hiện vật về lịch sử, văn hóa và cuộc sống người dân Quảng Trị từ thời tiền sử đến hiện đại. Bộ sưu tập đặc biệt về văn hóa Chăm Pa, hiện vật chiến tranh, đồ gốm sứ cổ và trang phục các dân tộc thiểu số vùng núi.`,
    hours: '07:30 – 11:00, 13:30 – 16:30 (Thứ 2–6; đóng cửa T7, CN)',
    admission: '20.000 VNĐ/người',
    phone: '0233 3555 678',
    website: '',
    rating: 4.2,
    reviews: 432,
    duration: '1–2 giờ',
    bestTime: 'Sáng (mát mẻ trong nhà)',
    highlight: false,
    tags: ['bảo tàng', 'lịch sử', 'văn hóa', 'giáo dục'],
    tips: [
      'Phù hợp cho gia đình có trẻ em — nhiều mô hình trực quan',
      'Đặt lịch hướng dẫn viên trước để được giải thích chi tiết',
    ],
    nearbyFood: ['Nhà hàng Đông Hà', 'Quán bún bò Đông Hà'],
    nearbyStay: ['Khách sạn Sài Gòn Đông Hà'],
    images: ['bao-tang-1.jpg'],
  },

  // ── ĐẶC BIỆT: ĐƯỜNG TRƯỜNG SƠN ───────────────────────────
  {
    id: 16,
    name: 'Di tích Đường Hồ Chí Minh – Quảng Trị',
    nameEn: 'Ho Chi Minh Trail Heritage Site',
    category: 'history',
    subcategory: 'Đường mòn lịch sử',
    lat: 16.7800,
    lng: 106.8500,
    address: 'Huyện Hướng Hóa và Đakrông, tỉnh Quảng Trị',
    description: `Đoạn Đường Hồ Chí Minh (đường Trường Sơn huyền thoại) chạy qua tỉnh Quảng Trị là một trong những đoạn đường gian khổ và anh hùng nhất. Ngày nay đã thành Quốc lộ 15D và đường Hồ Chí Minh hiện đại, nhưng vẫn lưu giữ nhiều di tích, trạm giao liên và ký ức lịch sử. Tuyến đường qua vùng núi Trường Sơn hùng vĩ với cảnh quan thiên nhiên tuyệt đẹp.`,
    hours: 'Mở cửa tự do',
    admission: 'Miễn phí',
    phone: '',
    website: '',
    rating: 4.5,
    reviews: 654,
    duration: 'Cả ngày (đi dọc tuyến)',
    bestTime: 'Tháng 3–5 và Tháng 9–11 (thời tiết đẹp)',
    highlight: false,
    tags: ['đường trường sơn', 'lịch sử', 'phong cảnh', 'phượt'],
    tips: [
      'Lý tưởng cho các biker phượt dọc đường Trường Sơn',
      'Dừng lại ở các điểm di tích bên đường để tìm hiểu lịch sử',
      'Thời tiết trên núi thay đổi nhanh — mang áo mưa',
    ],
    nearbyFood: ['Quán ăn dọc đường Hồ Chí Minh'],
    nearbyStay: ['Homestay dọc đường Trường Sơn'],
    images: ['ho-chi-minh-trail-1.jpg'],
  },

  // ============================================================
  //  QUẢNG BÌNH
  // ============================================================

  {
    id: 17,
    name: 'Động Phong Nha',
    nameEn: 'Phong Nha Cave',
    category: 'nature',
    subcategory: 'Hang động',
    province: 'Quảng Trị',
    lat: 17.5503,
    lng: 106.2864,
    address: 'Xã Sơn Trạch, huyện Bố Trạch, tỉnh Quảng Trị',
    description: `Động Phong Nha là viên ngọc quý của Di sản Thiên nhiên Thế giới Phong Nha – Kẻ Bàng. Hang nước dài nhất châu Á (7.729m đã khám phá) với những nhũ đá, măng đá lộng lẫy muôn hình muôn vẻ. Du khách đến bằng thuyền trên sông Son – hành trình ngắm cảnh thơ mộng qua rừng nguyên sinh trước khi vào lòng hang.`,
    hours: '07:00 – 17:00 (hàng ngày)',
    admission: '150.000 VNĐ/người (bao gồm thuyền)',
    phone: '0232 3677 678',
    website: 'phongnhakebang.vn',
    rating: 4.8,
    reviews: 8743,
    duration: '2–3 giờ',
    bestTime: 'Tháng 2–8 (tránh mùa lũ tháng 9–11)',
    highlight: true,
    tags: ['hang động', 'UNESCO', 'thuyền', 'nhũ đá', 'di sản thế giới'],
    tips: [
      'Đặt thuyền sớm buổi sáng (trước 9h) — đẹp hơn và ít đông người',
      'Thuê hướng dẫn viên địa phương để nghe câu chuyện về hang',
      'Mang áo khoác mỏng — trong hang chỉ 18–20°C quanh năm',
      'Kết hợp thăm Động Tiên Sơn (Tiên Sơn Cave) nằm trên cao gần đó',
    ],
    nearbyFood: ['Nhà hàng Phong Nha Lake House', 'Quán Phong Nha Farmstay', 'Riverside Bar'],
    nearbyStay: ['Phong Nha Farmstay', 'Chày Lập Ecolodge', 'Easy Tiger Hostel'],
    images: ['phong-nha-1.jpg', 'phong-nha-2.jpg', 'phong-nha-3.jpg'],
  },
  {
    id: 18,
    name: 'Động Thiên Đường',
    nameEn: 'Paradise Cave',
    category: 'nature',
    subcategory: 'Hang động',
    province: 'Quảng Trị',
    lat: 17.6158,
    lng: 106.1403,
    address: 'Xã Sơn Trạch, huyện Bố Trạch, tỉnh Quảng Trị',
    description: `Động Thiên Đường là hang khô dài nhất châu Á (31,4 km) và là một trong những hang đẹp nhất thế giới. Vẻ đẹp hoang sơ, hùng vĩ với những cột nhũ đá khổng lồ cao hàng chục mét, những hồ nước ngầm trong vắt màu ngọc bích. Tuyến khách thường tham quan 1 km có đèn chiếu sáng; tour khám phá đặc biệt đi sâu 7 km phải đặt trước qua Oxalis.`,
    hours: '07:30 – 16:30 (hàng ngày)',
    admission: '250.000 VNĐ/người',
    phone: '0232 3677 021',
    website: 'phongnhakebang.vn',
    rating: 4.9,
    reviews: 6218,
    duration: '2–4 giờ',
    bestTime: 'Tháng 2–8',
    highlight: true,
    tags: ['hang động', 'UNESCO', 'nhũ đá', 'kỳ quan', 'di sản thế giới'],
    tips: [
      'Đi xe điện vào điểm tham quan (3km từ cổng) — mua vé kèm',
      'Mang giày đế bằng, không trơn — đường trong hang ẩm ướt',
      'Tour 7km Adventure (Oxalis) cần đặt trước nhiều tuần — trải nghiệm đỉnh cao',
      'Tuyến 1km cơ bản vẫn cực kỳ ấn tượng với người lần đầu',
    ],
    nearbyFood: ['Quán cơm trước cổng Thiên Đường', 'Nhà hàng Phong Nha'],
    nearbyStay: ['Phong Nha Farmstay', 'Oxalis Camp'],
    images: ['thien-duong-1.jpg', 'thien-duong-2.jpg', 'thien-duong-3.jpg'],
  },
  {
    id: 19,
    name: 'Hang Sơn Đoòng',
    nameEn: 'Son Doong Cave',
    category: 'nature',
    subcategory: 'Hang động',
    province: 'Quảng Trị',
    lat: 17.5392,
    lng: 106.1714,
    address: 'Xã Tân Trạch, huyện Bố Trạch, tỉnh Quảng Trị',
    description: `Hang Sơn Đoòng là hang động lớn nhất thế giới – đủ chứa một tòa nhà 40 tầng bên trong. Được người dân địa phương phát hiện năm 1991 nhưng mãi đến 2009 mới được thế giới biết đến qua đoàn thám hiểm Anh. Bên trong hang có rừng nhiệt đới, sông ngầm, ánh sáng tự nhiên chiếu qua những hố sập khổng lồ. Tour 4 ngày 3 đêm với Oxalis Adventure là trải nghiệm thiên nhiên đỉnh cao nhất Việt Nam.`,
    hours: 'Tour cố định theo mùa (tháng 2–8), đặt trước 12 tháng',
    admission: '3.000 USD/người (tour 4N3Đ – bao gồm mọi chi phí)',
    phone: '0232 3675 055',
    website: 'oxalis.com.vn',
    rating: 5.0,
    reviews: 1247,
    duration: '4 ngày 3 đêm',
    bestTime: 'Tháng 2–8 (mùa khô)',
    highlight: true,
    tags: ['hang động', 'lớn nhất thế giới', 'UNESCO', 'trekking', 'oxalis', 'kỳ quan'],
    tips: [
      'Chỉ có Oxalis Adventure được cấp phép tổ chức tour Sơn Đoòng – đặt qua website chính thức',
      'Số lượng chỉ 1.000 khách/năm — đặt trước 12 tháng là bình thường',
      'Yêu cầu sức khỏe tốt, biết bơi cơ bản và không sợ độ cao',
      'Mọi chi phí ăn ngủ, porter, hướng dẫn viên đã bao gồm trong giá tour',
    ],
    nearbyFood: ['Base Camp Oxalis (được cung cấp trong tour)'],
    nearbyStay: ['Phong Nha Farmstay (trước và sau tour)', 'Easy Tiger Hostel'],
    images: ['son-doong-1.jpg', 'son-doong-2.jpg', 'son-doong-3.jpg'],
  },
  {
    id: 20,
    name: 'Hang Tối',
    nameEn: 'Dark Cave',
    category: 'nature',
    subcategory: 'Hang động & Phiêu lưu',
    province: 'Quảng Trị',
    lat: 17.6028,
    lng: 106.1414,
    address: 'Xã Sơn Trạch, huyện Bố Trạch, tỉnh Quảng Trị',
    description: `Hang Tối là điểm vui chơi mạo hiểm độc đáo bậc nhất Việt Nam. Du khách đu dây zipline dài 400m trên sông Son lao thẳng vào miệng hang, sau đó tự do bơi lội, chèo thuyền kayak khám phá bóng tối hoàn toàn, bơi qua hồ bùn khoáng chất và thách thức ở nhiều trạm leo núi trong lòng hang. Trải nghiệm cực kỳ phù hợp nhóm trẻ trung.`,
    hours: '07:30 – 16:00 (hàng ngày)',
    admission: '450.000 VNĐ/người (bao gồm zipline, kayak)',
    phone: '0232 3675 100',
    website: 'darkcave.vn',
    rating: 4.7,
    reviews: 4532,
    duration: '3–5 giờ',
    bestTime: 'Tháng 4–8 (nước cạn, zipline tốt nhất)',
    highlight: true,
    tags: ['hang động', 'zipline', 'mạo hiểm', 'kayak', 'bùn khoáng', 'phiêu lưu'],
    tips: [
      'Mặc đồ bơi vào — sẽ bị ướt hoàn toàn, rất vui',
      'Cần biết bơi cơ bản để tham gia an toàn',
      'Áo phao và mũ bảo hiểm được cung cấp miễn phí',
      'Đặt vé online sẽ tiết kiệm thời gian xếp hàng buổi sáng',
    ],
    nearbyFood: ['Quán ăn trước cổng Dark Cave', 'Nhà hàng bên sông Son'],
    nearbyStay: ['Easy Tiger Hostel', 'Phong Nha Farmstay'],
    images: ['hang-toi-1.jpg', 'hang-toi-2.jpg'],
  },
  {
    id: 21,
    name: 'Hang En',
    nameEn: 'En Cave',
    category: 'nature',
    subcategory: 'Hang động & Trekking',
    province: 'Quảng Trị',
    lat: 17.5214,
    lng: 106.1347,
    address: 'Xã Tân Trạch, huyện Bố Trạch, tỉnh Quảng Trị',
    description: `Hang En là hang động lớn thứ ba thế giới và là "bậc thềm" đi vào Sơn Đoòng. Hành trình 2 ngày 1 đêm qua rừng nguyên sinh Kẻ Bàng, vượt sông, leo núi đến căn cứ dưới lòng hang rộng lớn với vòm hang cao 100m. Cắm trại đêm trong lòng hang, nghe tiếng én bay vào lúc bình minh — khoảnh khắc không thể quên trong cuộc đời.`,
    hours: 'Tour 2N1Đ, xuất phát sáng sớm',
    admission: '4.500.000 VNĐ/người (tour 2N1Đ qua Oxalis)',
    phone: '0232 3675 055',
    website: 'oxalis.com.vn',
    rating: 4.9,
    reviews: 2876,
    duration: '2 ngày 1 đêm',
    bestTime: 'Tháng 2–8',
    highlight: true,
    tags: ['hang động', 'trekking', 'cắm trại', 'oxalis', 'kỳ quan', 'én hang'],
    tips: [
      'Hành trình 11km qua rừng — cần thể lực tốt, không phù hợp người già/trẻ nhỏ',
      'Oxalis cung cấp đầy đủ: lều cắm trại, bữa ăn, hướng dẫn viên, porter',
      'Đặt trước ít nhất 1–2 tháng vì số lượng hạn chế',
      'Đây là lựa chọn tuyệt vời cho ai muốn trải nghiệm Phong Nha mà không đủ ngân sách Sơn Đoòng',
    ],
    nearbyFood: ['Được cung cấp trong tour'],
    nearbyStay: ['Phong Nha Farmstay (trước tour)'],
    images: ['hang-en-1.jpg', 'hang-en-2.jpg'],
  },
  {
    id: 22,
    name: 'Suối Nước Moọc',
    nameEn: 'Mooc Spring',
    category: 'nature',
    subcategory: 'Suối & Sinh thái',
    province: 'Quảng Trị',
    lat: 17.5806,
    lng: 106.1814,
    address: 'Xã Sơn Trạch, huyện Bố Trạch, tỉnh Quảng Trị',
    description: `Suối Nước Moọc là viên ngọc xanh trong lòng rừng Phong Nha – Kẻ Bàng. Nước suối trong vắt màu ngọc lam tuôn chảy từ khe đá vôi, nhiệt độ mát lạnh dễ chịu quanh năm. Khu du lịch sinh thái được quy hoạch bài bản với hệ thống cầu treo, bè tre đi bộ trên nước, điểm bơi lội được đánh giá là đẹp nhất trong các địa điểm của Phong Nha.`,
    hours: '07:30 – 17:30 (hàng ngày)',
    admission: '80.000 VNĐ/người',
    phone: '0232 3677 456',
    website: '',
    rating: 4.6,
    reviews: 3421,
    duration: '2–4 giờ',
    bestTime: 'Tháng 4–9 (mùa hè — nước dâng đẹp, trời nóng bơi càng thích)',
    highlight: false,
    tags: ['suối', 'bơi lội', 'sinh thái', 'rừng', 'phong nha'],
    tips: [
      'Mang theo đồ bơi và sandal chống trơn',
      'Ghé trưa để tránh nắng, bơi mát trong lành',
      'Có thể thuê áo phao tại chỗ',
      'Kết hợp tham quan cùng ngày với Hang Tối (cách 3km)',
    ],
    nearbyFood: ['Nhà hàng trong khu du lịch Nước Moọc', 'Phong Nha Farmstay'],
    nearbyStay: ['Phong Nha Farmstay', 'Chày Lập Ecolodge'],
    images: ['nuoc-mooc-1.jpg', 'nuoc-mooc-2.jpg'],
  },
  {
    id: 23,
    name: 'Vườn Quốc gia Phong Nha – Kẻ Bàng',
    nameEn: 'Phong Nha-Ke Bang National Park',
    category: 'nature',
    subcategory: 'Vườn Quốc gia',
    province: 'Quảng Trị',
    lat: 17.5447,
    lng: 106.2000,
    address: 'Huyện Bố Trạch, tỉnh Quảng Trị',
    description: `Vườn Quốc gia Phong Nha – Kẻ Bàng rộng 123.326 ha, được UNESCO công nhận Di sản Thiên nhiên Thế giới (2003, mở rộng 2015). Nơi đây sở hữu hệ thống hang động vôi cổ nhất, lớn nhất thế giới (khoảng 300 hang đã khám phá) và hệ sinh thái rừng nhiệt đới nguyên sinh đặc biệt phong phú, là môi trường sống của nhiều loài động thực vật đặc hữu quý hiếm.`,
    hours: 'Mở cửa tự do (các điểm tham quan có giờ riêng)',
    admission: 'Vé vào các điểm tham quan riêng',
    phone: '0232 3677 021',
    website: 'phongnhakebang.vn',
    rating: 4.9,
    reviews: 5600,
    duration: '2–7 ngày',
    bestTime: 'Tháng 2–8 (mùa khô)',
    highlight: true,
    tags: ['UNESCO', 'vườn quốc gia', 'hang động', 'rừng nhiệt đới', 'di sản thế giới'],
    tips: [
      'Lên kế hoạch ít nhất 2–3 ngày để tham quan đầy đủ các điểm chính',
      'Book tour qua Oxalis Adventure hoặc ban quản lý VQG cho trải nghiệm an toàn',
      'Mang kem chống muỗi và côn trùng khi đi rừng',
    ],
    nearbyFood: ['Phong Nha Farmstay', 'Nhà hàng Sơn Trạch'],
    nearbyStay: ['Phong Nha Farmstay', 'Chày Lập Ecolodge', 'Easy Tiger Hostel'],
    images: ['pnkb-1.jpg', 'pnkb-2.jpg'],
  },
  {
    id: 24,
    name: 'Bãi biển Nhật Lệ',
    nameEn: 'Nhat Le Beach',
    category: 'beach',
    subcategory: 'Bãi biển thành phố',
    province: 'Quảng Trị',
    lat: 17.4522,
    lng: 106.6197,
    address: 'TP. Đồng Hới, tỉnh Quảng Trị',
    description: `Bãi biển Nhật Lệ là trung tâm nghỉ mát của thành phố Đồng Hới — bờ cát trắng mịn dài hơn 2km, nước biển xanh trong, sóng vừa phải. Buổi sáng có chợ hải sản tươi trực tiếp từ thuyền ngư dân; buổi tối là hàng loạt nhà hàng hải sản ven bờ tấp nập. Gần khách sạn và tiện di chuyển từ ga tàu Đồng Hới chỉ 3km.`,
    hours: 'Mở cửa tự do',
    admission: 'Miễn phí',
    phone: '',
    website: '',
    rating: 4.4,
    reviews: 5217,
    duration: 'Nửa ngày đến cả ngày',
    bestTime: 'Tháng 5–8 (mùa hè)',
    highlight: false,
    tags: ['biển', 'tắm biển', 'hải sản', 'đồng hới'],
    tips: [
      'Mua hải sản tươi từ thuyền 5–7h sáng — rẻ nhất và tươi nhất',
      'Bơi buổi sáng sớm trước 9h và chiều sau 16h để tránh nắng gắt',
      'Khu nhà hàng ven biển đường Trần Hưng Đạo rất sầm uất buổi tối',
    ],
    nearbyFood: ['Nhà hàng Hải Trang', 'Quán Cô Tám Hải Sản', 'Chợ đêm Nhật Lệ'],
    nearbyStay: ['Sun Spa Resort', 'Khách sạn Sài Gòn Quảng Trị', 'Sun Hotel Đồng Hới'],
    images: ['nhat-le-1.jpg', 'nhat-le-2.jpg'],
  },
  {
    id: 25,
    name: 'Bãi biển Bảo Ninh',
    nameEn: 'Bao Ninh Beach',
    category: 'beach',
    subcategory: 'Bãi biển hoang sơ',
    province: 'Quảng Trị',
    lat: 17.4731,
    lng: 106.6322,
    address: 'Xã Bảo Ninh, TP. Đồng Hới, tỉnh Quảng Trị',
    description: `Bãi biển Bảo Ninh nằm đối diện thành phố Đồng Hới qua cửa sông Nhật Lệ, nổi tiếng với bờ cát trắng dài, sóng mạnh hơn Nhật Lệ, không khí trong lành và ít đông hơn. Đây là làng chài truyền thống với những chuyến thuyền thúng ra khơi đặc trưng của ngư dân miền Trung. Sang cầu Nhật Lệ hoặc đi phà ngắn từ bến tàu.`,
    hours: 'Mở cửa tự do',
    admission: 'Miễn phí',
    phone: '',
    website: '',
    rating: 4.5,
    reviews: 2134,
    duration: 'Nửa ngày',
    bestTime: 'Tháng 5–8',
    highlight: false,
    tags: ['biển', 'làng chài', 'hoang sơ', 'thuyền thúng'],
    tips: [
      'Đi cầu Nhật Lệ 2 hoặc phà để sang — phà rẻ hơn và thú vị hơn',
      'Sóng mạnh hơn bãi Nhật Lệ — thích hợp người biết bơi',
      'Chụp ảnh thuyền thúng buổi sáng sớm rất đẹp',
    ],
    nearbyFood: ['Quán hải sản Bảo Ninh', 'Nhà hàng bờ biển'],
    nearbyStay: ['Sun Spa Resort', 'Khách sạn Phú Quý Bảo Ninh'],
    images: ['bao-ninh-1.jpg', 'bao-ninh-2.jpg'],
  },
  {
    id: 26,
    name: 'Bãi Đá Nhảy',
    nameEn: 'Da Nhay Beach',
    category: 'beach',
    subcategory: 'Bãi biển hoang sơ',
    province: 'Quảng Trị',
    lat: 17.7283,
    lng: 106.6417,
    address: 'Xã Thanh Trạch, huyện Bố Trạch, tỉnh Quảng Trị',
    description: `Bãi Đá Nhảy là bãi biển hoang sơ đẹp nhất vùng Bắc Quảng Trị — nơi những khối đá granit khổng lồ hàng triệu năm tuổi nhô lên giữa bờ cát trắng tạo nên cảnh quan kỳ ảo độc nhất vô nhị. Sóng biển mạnh vỗ vào đá tung bọt trắng xóa. Hầu như không có dịch vụ du lịch — du khách tự mang theo đồ ăn, nước uống và tận hưởng sự hoang sơ tuyệt đối.`,
    hours: 'Mở cửa tự do',
    admission: 'Miễn phí',
    phone: '',
    website: '',
    rating: 4.7,
    reviews: 3218,
    duration: 'Nửa ngày đến cả ngày',
    bestTime: 'Tháng 4–8 (tránh mùa bão)',
    highlight: true,
    tags: ['biển', 'đá granit', 'hoang sơ', 'check-in', 'thiên nhiên'],
    tips: [
      'Không có dịch vụ ăn uống — tự chuẩn bị đồ ăn và nước uống',
      'Đường vào từ QL1A, cách Đồng Hới ~35km về phía bắc',
      'KHÔNG bơi vùng có đá ngầm — chỉ chụp ảnh và tắm vùng cát an toàn',
      'Thuê xe máy từ Đồng Hới để tự do ghé thăm',
      'Sáng sớm có ánh sáng đẹp cho nhiếp ảnh — ít khách nhất',
    ],
    nearbyFood: ['Tự mang theo'],
    nearbyStay: ['Khách sạn tại Đồng Hới (35km)'],
    images: ['da-nhay-1.jpg', 'da-nhay-2.jpg', 'da-nhay-3.jpg'],
  },
  {
    id: 27,
    name: 'Vũng Chùa – Đảo Yến (Mộ Đại tướng Võ Nguyên Giáp)',
    nameEn: 'Vung Chua – Dao Yen (General Giap\'s Resting Place)',
    category: 'history',
    subcategory: 'Di tích Quốc gia',
    province: 'Quảng Trị',
    lat: 17.9117,
    lng: 106.5617,
    address: 'Xã Quảng Đông, huyện Quảng Trạch, tỉnh Quảng Trị',
    description: `Vũng Chùa – Đảo Yến là nơi an nghỉ vĩnh hằng của Đại tướng Võ Nguyên Giáp (1911–2013) — người anh hùng dân tộc, Tổng Tư lệnh quân đội nhân dân Việt Nam. Đây là nguyện vọng của ông: được nằm lại giữa non nước quê hương (nay thuộc vùng Bắc Quảng Trị), nhìn ra biển Đông. Khu mộ đơn giản, trang nghiêm giữa cảnh trời nước hữu tình. Hàng triệu lượt người hành hương tưởng nhớ mỗi năm.`,
    hours: '07:00 – 18:00 (hàng ngày)',
    admission: 'Miễn phí',
    phone: '',
    website: '',
    rating: 4.9,
    reviews: 9876,
    duration: '30–60 phút',
    bestTime: 'Quanh năm (đặc biệt dịp 4/10 — ngày mất của Đại tướng)',
    highlight: true,
    tags: ['lịch sử', 'đại tướng', 'võ nguyên giáp', 'tâm linh', 'di tích quốc gia'],
    tips: [
      'Ăn mặc trang nghiêm, không mặc đồ sặc sỡ khi đến viếng',
      'Không ồn ào, không chụp ảnh tự sướng thiếu tôn trọng',
      'Cách Đồng Hới khoảng 50km về phía bắc, đi QL1A',
      'Kết hợp thăm Đèo Ngang cách đó 15km về phía bắc',
    ],
    nearbyFood: ['Quán ăn xã Quảng Đông'],
    nearbyStay: ['Nhà nghỉ Quảng Trạch', 'Khách sạn Đồng Hới (50km)'],
    images: ['vung-chua-1.jpg', 'vung-chua-2.jpg'],
  },
  {
    id: 28,
    name: 'Quảng Bình Quan',
    nameEn: 'Quang Binh Quan Gate',
    category: 'history',
    subcategory: 'Cổng lịch sử – Di tích Quốc gia',
    province: 'Quảng Trị',
    lat: 17.4681,
    lng: 106.5971,
    address: 'Phường Đồng Phú, TP. Đồng Hới, tỉnh Quảng Trị',
    description: `Quảng Bình Quan là cổng thành lịch sử xây dựng từ thời Gia Long (đầu thế kỷ XIX) — biểu tượng của Quảng Bình. Cổng vòm đá uy nghi nằm giữa trung tâm thành phố Đồng Hới, là chứng nhân lịch sử qua các cuộc chiến tranh và thăng trầm của vùng đất. Được công nhận Di tích Quốc gia, cổng còn lưu giữ nguyên vẹn kiến trúc đặc trưng thời Nguyễn.`,
    hours: 'Mở cửa tự do (24/7)',
    admission: 'Miễn phí',
    phone: '',
    website: '',
    rating: 4.5,
    reviews: 2341,
    duration: '20–30 phút',
    bestTime: 'Sáng sớm hoặc chiều tối — ánh sáng đẹp, mát mẻ',
    highlight: false,
    tags: ['lịch sử', 'kiến trúc', 'nhà nguyễn', 'di tích quốc gia', 'đồng hới'],
    tips: [
      'Điểm check-in không thể bỏ qua khi đến Đồng Hới',
      'Nằm ngay trung tâm thành phố, dễ kết hợp với tham quan các điểm khác',
    ],
    nearbyFood: ['Chợ Đồng Hới', 'Quán ăn sáng phố cổ'],
    nearbyStay: ['Khách sạn Sài Gòn Quảng Trị', 'Sun Hotel Đồng Hới'],
    images: ['qbq-1.jpg', 'qbq-2.jpg'],
  },
  {
    id: 29,
    name: 'Lũy Thầy (Lũy Đào Duy Từ)',
    nameEn: 'Dao Duy Tu Wall',
    category: 'history',
    subcategory: 'Thành lũy cổ',
    province: 'Quảng Trị',
    lat: 17.5500,
    lng: 106.5750,
    address: 'Huyện Bố Trạch, tỉnh Quảng Trị',
    description: `Lũy Thầy là công trình phòng thủ do danh thần Đào Duy Từ thiết kế và xây dựng năm 1630–1631 theo lệnh chúa Nguyễn Phúc Nguyên, kéo dài 12km từ núi Đầu Mâu đến cửa biển Nhật Lệ. Lũy thành chiến lược này đã giúp chúa Nguyễn ngăn chặn các cuộc tấn công của chúa Trịnh trong suốt nhiều thập kỷ, là một trong những công trình quân sự quan trọng nhất lịch sử Việt Nam thế kỷ XVII.`,
    hours: 'Mở cửa tự do',
    admission: 'Miễn phí',
    phone: '',
    website: '',
    rating: 4.2,
    reviews: 876,
    duration: '30–60 phút',
    bestTime: 'Quanh năm',
    highlight: false,
    tags: ['lịch sử', 'lũy thành', 'đào duy từ', 'chúa nguyễn', 'di tích'],
    tips: [
      'Cần hướng dẫn viên hoặc nghiên cứu trước mới hiểu được giá trị lịch sử',
      'Kết hợp tham quan cùng Quảng Bình Quan và chùa Non trong một ngày',
    ],
    nearbyFood: ['Quán ăn dọc đường QL1A'],
    nearbyStay: ['Khách sạn Đồng Hới'],
    images: ['luy-thay-1.jpg'],
  },
  {
    id: 30,
    name: 'Đèo Ngang',
    nameEn: 'Ngang Pass',
    category: 'nature',
    subcategory: 'Đèo núi – Danh thắng',
    province: 'Quảng Trị',
    lat: 18.0483,
    lng: 106.5306,
    address: 'Ranh giới Quảng Trị – Hà Tĩnh (QL1A)',
    description: `Đèo Ngang là ranh giới địa lý giữa Quảng Trị và Hà Tĩnh, cao 256m so với mặt biển, nổi tiếng qua bài thơ "Qua Đèo Ngang" của Bà Huyện Thanh Quan (thế kỷ XIX): "Bước tới Đèo Ngang bóng xế tà / Cỏ cây chen đá lá chen hoa...". Từ đỉnh đèo, cảnh biển và núi rừng trùng điệp mở ra tầm mắt. Có Hoành Sơn Quan — cửa ải cổ từ thời nhà Lê.`,
    hours: 'Mở cửa tự do (24/7)',
    admission: 'Miễn phí',
    phone: '',
    website: '',
    rating: 4.5,
    reviews: 3214,
    duration: '30–60 phút',
    bestTime: 'Sáng sớm (5–8h) — ít xe và ngắm bình minh biển',
    highlight: false,
    tags: ['đèo', 'thơ', 'lịch sử', 'cảnh quan', 'biên giới tỉnh'],
    tips: [
      'Dừng lại chụp ảnh ở đỉnh đèo phía Quảng Trị — view biển tuyệt đẹp',
      'Hoành Sơn Quan (cổng ải cũ) nằm bên trái khi từ nam ra bắc',
      'Cẩn thận khi lái xe qua đèo — đường quanh co, nhiều xe tải',
    ],
    nearbyFood: ['Quán nước đỉnh đèo'],
    nearbyStay: ['Nhà nghỉ chân đèo (Hà Tĩnh/Quảng Trị)'],
    images: ['deo-ngang-1.jpg', 'deo-ngang-2.jpg'],
  },
  {
    id: 31,
    name: 'Hệ thống hang Tu Lan',
    nameEn: 'Tu Lan Cave System',
    category: 'nature',
    subcategory: 'Hang động & Trekking',
    province: 'Quảng Trị',
    lat: 17.7667,
    lng: 105.9500,
    address: 'Xã Tân Hóa, huyện Minh Hóa, tỉnh Quảng Trị',
    description: `Hệ thống hang Tu Lan gồm 10 hang động được kết nối bởi những dòng sông ngầm và rừng nguyên sinh — một "Phong Nha thu nhỏ" hoàn toàn hoang sơ và chưa bị khai thác đại trà. Tour 2–4 ngày vượt rừng, bơi sông ngầm, ngủ trong hang và cắm trại bên suối. Được National Geographic xếp vào top trải nghiệm khám phá hang động hàng đầu thế giới.`,
    hours: 'Tour 2–4 ngày, xuất phát từ Phong Nha town',
    admission: '3.500.000 – 8.500.000 VNĐ/người (tùy tour dài ngắn)',
    phone: '0232 3675 055',
    website: 'oxalis.com.vn',
    rating: 4.9,
    reviews: 1432,
    duration: '2–4 ngày',
    bestTime: 'Tháng 3–8 (mùa khô)',
    highlight: false,
    tags: ['hang động', 'trekking', 'cắm trại', 'sông ngầm', 'oxalis', 'hoang sơ'],
    tips: [
      'Chỉ tổ chức qua Oxalis Adventure — đặt trước ít nhất 2 tháng',
      'Phải biết bơi cơ bản (bơi trong hang tối cần áo phao)',
      'Phù hợp người yêu khám phá mạo hiểm, không phù hợp gia đình có trẻ nhỏ',
    ],
    nearbyFood: ['Được cung cấp trong tour'],
    nearbyStay: ['Phong Nha Farmstay (trước tour)'],
    images: ['tu-lan-1.jpg', 'tu-lan-2.jpg'],
  },
  {
    id: 32,
    name: 'Hang Va',
    nameEn: 'Va Cave',
    category: 'nature',
    subcategory: 'Hang động',
    province: 'Quảng Trị',
    lat: 17.5667,
    lng: 106.1167,
    address: 'Xã Sơn Trạch, huyện Bố Trạch, tỉnh Quảng Trị',
    description: `Hang Va được mệnh danh là "thiên đường nhũ đá" với vẻ đẹp kỳ ảo của hàng nghìn cột nhũ đá hình tháp nhọn mọc từ dưới lên — cảnh quan chỉ có ở đây và Hang Tiên Sơn. Hang nước thơ mộng chảy xuyên qua, du khách bơi qua những buồng hang huyền bí. Tour 1 ngày qua Oxalis, hành trình khoảng 10km đi bộ trong rừng.`,
    hours: 'Tour 1 ngày, xuất phát từ Phong Nha',
    admission: '3.200.000 VNĐ/người (tour 1 ngày)',
    phone: '0232 3675 055',
    website: 'oxalis.com.vn',
    rating: 4.8,
    reviews: 987,
    duration: '1 ngày',
    bestTime: 'Tháng 3–8',
    highlight: false,
    tags: ['hang động', 'nhũ đá', 'sông ngầm', 'trekking', 'oxalis'],
    tips: [
      'Kết hợp tour Hang Va – Hang Nước Nứt trong cùng 1 ngày (combo tour)',
      'Phải biết bơi — có đoạn bơi trong hang tối ngắn',
      'Mang theo áo ấm trong hang và giày leo núi chống trơn',
    ],
    nearbyFood: ['Được cung cấp trong tour'],
    nearbyStay: ['Phong Nha Farmstay'],
    images: ['hang-va-1.jpg'],
  },
  {
    id: 33,
    name: 'Đảo Hòn La',
    nameEn: 'Hon La Island',
    category: 'beach',
    subcategory: 'Đảo & Vịnh',
    province: 'Quảng Trị',
    lat: 17.8336,
    lng: 106.6536,
    address: 'Huyện Quảng Trạch, tỉnh Quảng Trị',
    description: `Đảo Hòn La là đảo nhỏ hoang sơ ngoài khơi vùng Bắc Quảng Trị, nơi có vịnh biển kín gió với làn nước trong xanh, bãi cát trắng nguyên sơ và rặng san hô còn khá nguyên vẹn. Đảo có cảng nước sâu chiến lược, nhưng phần lớn diện tích vẫn là rừng nhiệt đới chưa bị xâm phạm. Thuyền ra đảo từ cảng Hòn La khoảng 20 phút.`,
    hours: 'Tour tàu theo giờ tàu chạy',
    admission: 'Vé tàu: 100.000–150.000 VNĐ/chiều',
    phone: '',
    website: '',
    rating: 4.3,
    reviews: 654,
    duration: 'Nửa ngày đến cả ngày',
    bestTime: 'Tháng 5–8 (biển lặng)',
    highlight: false,
    tags: ['đảo', 'biển', 'hoang sơ', 'lặn biển', 'quảng trạch'],
    tips: [
      'Cần kiểm tra lịch tàu trước — không thường xuyên như đảo Cồn Cỏ',
      'Mang đồ ăn và nước uống tự túc',
      'Phù hợp cho camping qua đêm nếu xin phép địa phương',
    ],
    nearbyFood: ['Tự mang theo'],
    nearbyStay: ['Nhà nghỉ Quảng Trạch', 'Khách sạn Đồng Hới (cách 50km)'],
    images: ['hon-la-1.jpg'],
  },
  {
    id: 34,
    name: 'Nhà thờ Tam Tòa',
    nameEn: 'Tam Toa Church Ruins',
    category: 'history',
    subcategory: 'Di tích chiến tranh',
    province: 'Quảng Trị',
    lat: 17.4775,
    lng: 106.6028,
    address: 'Đường Nguyễn Du, TP. Đồng Hới, tỉnh Quảng Trị',
    description: `Nhà thờ Tam Tòa là nhà thờ Công giáo xây dựng năm 1940, bị phá hủy hoàn toàn trong các đợt ném bom của Mỹ năm 1965. Chỉ còn lại một tháp chuông đứng trơ trọi giữa nền gạch vỡ — trở thành biểu tượng của đau thương và ý chí kiên cường của người dân Đồng Hới. Là di tích lịch sử quan trọng, được giữ nguyên hiện trạng như lời nhắc về hậu quả chiến tranh.`,
    hours: 'Mở cửa tự do',
    admission: 'Miễn phí',
    phone: '',
    website: '',
    rating: 4.4,
    reviews: 1876,
    duration: '20–30 phút',
    bestTime: 'Chiều tối — ánh hoàng hôn qua tháp chuông rất đẹp',
    highlight: false,
    tags: ['chiến tranh', 'nhà thờ', 'lịch sử', 'di tích', 'đồng hới'],
    tips: [
      'Điểm tham quan nhanh, kết hợp với Quảng Bình Quan và bờ biển Nhật Lệ',
      'Chụp ảnh đẹp nhất lúc hoàng hôn khi ánh sáng vàng rọi qua tháp chuông',
    ],
    nearbyFood: ['Chợ Đồng Hới (cách 500m)', 'Quán cà phê phố Đồng Hới'],
    nearbyStay: ['Khách sạn Sài Gòn Quảng Trị', 'Sun Hotel'],
    images: ['tam-toa-1.jpg', 'tam-toa-2.jpg'],
  },
  {
    id: 35,
    name: 'Hồ Bàu Tró',
    nameEn: 'Bau Tro Lake',
    category: 'nature',
    subcategory: 'Hồ nước ngọt',
    province: 'Quảng Trị',
    lat: 17.4903,
    lng: 106.6447,
    address: 'TP. Đồng Hới, tỉnh Quảng Trị',
    description: `Hồ Bàu Tró là hồ nước ngọt tự nhiên hiếm hoi nằm ngay sát bờ biển — chỉ cách biển Nhật Lệ chưa đầy 1km nhưng hoàn toàn là nước ngọt. Xung quanh hồ là rừng phi lao xanh mát, mặt nước trong xanh phản chiếu bầu trời. Đây cũng là địa điểm khảo cổ quan trọng khi các nhà khoa học tìm thấy dấu tích cư dân thời đồ đá mới tại đây.`,
    hours: 'Mở cửa tự do',
    admission: 'Miễn phí',
    phone: '',
    website: '',
    rating: 4.2,
    reviews: 1234,
    duration: '30–60 phút',
    bestTime: 'Sáng sớm — mặt hồ phẳng lặng, ánh sáng đẹp',
    highlight: false,
    tags: ['hồ', 'thiên nhiên', 'phi lao', 'bình yên', 'đồng hới'],
    tips: [
      'Điểm tham quan nhẹ nhàng, phù hợp đi bộ quanh hồ buổi sáng',
      'Kết hợp với bãi biển Nhật Lệ cách đó chưa đầy 1km',
    ],
    nearbyFood: ['Nhà hàng ven hồ Bàu Tró'],
    nearbyStay: ['Sun Spa Resort (gần đó)', 'Khách sạn Đồng Hới'],
    images: ['bau-tro-1.jpg'],
  },
  {
    id: 36,
    name: 'Cổng Trời Minh Hóa',
    nameEn: 'Minh Hoa Heaven Gate',
    category: 'nature',
    subcategory: 'Đèo núi & Biên giới',
    province: 'Quảng Trị',
    lat: 17.8944,
    lng: 105.7167,
    address: 'Huyện Minh Hóa, tỉnh Quảng Trị',
    description: `"Cổng Trời" Minh Hóa là con đèo hùng vĩ trên đường vào huyện Minh Hóa — vùng núi cao giáp Lào với phong cảnh rừng nguyên sinh hoang dã. Từ đây nhìn xuống thung lũng Minh Hóa xanh biếc, mây vờn trên đỉnh núi. Đây là vùng sinh sống của đồng bào Rục, Sách, Mày — các dân tộc thiểu số với phong tục tập quán độc đáo.`,
    hours: 'Mở cửa tự do',
    admission: 'Miễn phí',
    phone: '',
    website: '',
    rating: 4.4,
    reviews: 876,
    duration: '1–3 giờ',
    bestTime: 'Tháng 10–4 (mát, ít sương mù hơn mùa hè)',
    highlight: false,
    tags: ['đèo', 'núi rừng', 'dân tộc thiểu số', 'biên giới', 'phiêu lưu'],
    tips: [
      'Cần xe máy hoặc ô tô địa hình — đường đèo gồ ghề',
      'Ghé thăm bản làng người Rục — cần có sự giới thiệu từ địa phương',
      'Mang áo ấm — khí hậu miền núi lạnh hơn đồng bằng nhiều',
    ],
    nearbyFood: ['Quán ăn tại thị trấn Quy Đạt'],
    nearbyStay: ['Nhà nghỉ Minh Hóa'],
    images: ['cong-troi-1.jpg'],
  },
  {
    id: 37,
    name: 'Bãi biển Lý Hòa',
    nameEn: 'Ly Hoa Beach',
    category: 'beach',
    subcategory: 'Bãi biển làng chài',
    province: 'Quảng Trị',
    lat: 17.9500,
    lng: 106.5417,
    address: 'Xã Hải Trạch, huyện Bố Trạch, tỉnh Quảng Trị',
    description: `Bãi biển Lý Hòa nằm trong vịnh nhỏ yên tĩnh với bờ cát trắng, rừng phi lao xanh và làng chài truyền thống. Ít người biết đến hơn Nhật Lệ hay Đá Nhảy nên vẫn giữ được vẻ hoang sơ. Nơi đây còn lưu giữ những chiếc ghe bầu — loại thuyền buôn truyền thống của ngư dân miền Trung. Cảnh hoàng hôn từ bãi Lý Hòa được nhiếp ảnh gia đánh giá rất cao.`,
    hours: 'Mở cửa tự do',
    admission: 'Miễn phí',
    phone: '',
    website: '',
    rating: 4.5,
    reviews: 1087,
    duration: 'Nửa ngày',
    bestTime: 'Tháng 5–8',
    highlight: false,
    tags: ['biển', 'làng chài', 'hoang sơ', 'phi lao', 'nhiếp ảnh'],
    tips: [
      'Chụp ảnh hoàng hôn từ bãi rất đẹp — ít du khách',
      'Có thể mua hải sản tươi trực tiếp từ ngư dân vào buổi sáng sớm',
    ],
    nearbyFood: ['Quán cá tươi làng Lý Hòa'],
    nearbyStay: ['Nhà nghỉ dân địa phương', 'Khách sạn Đồng Hới (55km)'],
    images: ['ly-hoa-1.jpg'],
  },
  {
    id: 38,
    name: 'Bản Đoòng',
    nameEn: 'Doong Village',
    category: 'nature',
    subcategory: 'Làng dân tộc & Sinh thái',
    province: 'Quảng Trị',
    lat: 17.4944,
    lng: 106.1281,
    address: 'Xã Tân Trạch, huyện Bố Trạch, tỉnh Quảng Trị',
    description: `Bản Đoòng là ngôi làng nhỏ của người Bru – Vân Kiều nằm ngay cạnh Hang Sơn Đoòng, sâu trong lòng Vườn Quốc gia Phong Nha – Kẻ Bàng. Trước khi Sơn Đoòng được thế giới biết đến, đây chỉ là bản làng hẻo lánh với vài chục hộ dân sinh sống giữa rừng già. Nay bản trở thành một phần hành trình khám phá Sơn Đoòng — du khách ngủ lại và trải nghiệm cuộc sống người Vân Kiều.`,
    hours: 'Chỉ ghé thăm trong khuôn khổ tour Sơn Đoòng / Hang En',
    admission: 'Bao gồm trong giá tour',
    phone: '',
    website: 'oxalis.com.vn',
    rating: 4.7,
    reviews: 543,
    duration: '1 ngày (trong tour đa ngày)',
    bestTime: 'Tháng 2–8',
    highlight: false,
    tags: ['văn hóa dân tộc', 'vân kiều', 'sinh thái', 'rừng nguyên sinh', 'sơn đoòng'],
    tips: [
      'Không thể đến riêng — chỉ trong tour Sơn Đoòng / Hang En của Oxalis',
      'Tôn trọng phong tục tập quán người Vân Kiều khi ghé thăm bản',
    ],
    nearbyFood: ['Được cung cấp bởi người dân địa phương trong tour'],
    nearbyStay: ['Lều cắm trại trong tour'],
    images: ['ban-doong-1.jpg'],
  },
  {
    id: 39,
    name: 'Đường 20 Quyết Thắng',
    nameEn: 'Road 20 – Quyet Thang Historical Route',
    category: 'history',
    subcategory: 'Đường lịch sử chiến tranh',
    province: 'Quảng Trị',
    lat: 17.4667,
    lng: 106.1833,
    address: 'Huyện Bố Trạch, tỉnh Quảng Trị',
    description: `Đường 20 Quyết Thắng dài 125km xuyên qua dãy Trường Sơn, được mở khẩn cấp trong 56 ngày đêm năm 1966 bởi 8.000 thanh niên xung phong và bộ đội, dưới mưa bom ác liệt. Con đường mở thêm tuyến vận chuyển vào miền Nam khi đường 12A bị đánh phá dữ dội. Nhiều trọng điểm đánh phá ác liệt nhất trên con đường này đã được công nhận Di tích Lịch sử Quốc gia.`,
    hours: 'Mở cửa tự do',
    admission: 'Miễn phí',
    phone: '',
    website: '',
    rating: 4.3,
    reviews: 654,
    duration: 'Cả ngày (đi dọc tuyến)',
    bestTime: 'Tháng 3–5 và 9–11',
    highlight: false,
    tags: ['lịch sử', 'đường trường sơn', 'chiến tranh', 'di tích'],
    tips: [
      'Thuê xe máy hoặc ô tô để đi dọc tuyến đường lịch sử',
      'Ghé các biển chú thích tại các điểm đánh phá ác liệt',
      'Kết hợp với tham quan vùng Phong Nha',
    ],
    nearbyFood: ['Quán ăn dọc đường 20'],
    nearbyStay: ['Phong Nha Farmstay'],
    images: ['duong-20-1.jpg'],
  },
  {
    id: 40,
    name: 'Chày Lập Farmstay & Ecolodge',
    nameEn: 'Chay Lap Farmstay',
    category: 'nature',
    subcategory: 'Eco Lodge & Nghỉ dưỡng thiên nhiên',
    province: 'Quảng Trị',
    lat: 17.6014,
    lng: 106.1647,
    address: 'Xã Sơn Trạch, huyện Bố Trạch, tỉnh Quảng Trị',
    description: `Chày Lập Farmstay là khu nghỉ dưỡng sinh thái đẹp nhất khu vực Phong Nha, nằm trên bãi sông Song với những bungalow gỗ thơ mộng ẩn mình giữa rừng nhiệt đới. Tắm sông trong vắt, ngủ nghe tiếng côn trùng rừng, ăn sáng với đặc sản địa phương — trải nghiệm thiên nhiên thuần khiết mà hiếm nơi nào ở Việt Nam sánh kịp. Được National Geographic vinh danh một trong những eco-lodge tốt nhất Đông Nam Á.`,
    hours: 'Check-in: 14:00 | Check-out: 11:00',
    admission: '800.000 – 2.500.000 VNĐ/đêm',
    phone: '0232 3675 135',
    website: 'chaylap.com',
    rating: 4.9,
    reviews: 2341,
    duration: '1–3 đêm',
    bestTime: 'Tháng 3–9 (mùa khô)',
    highlight: true,
    tags: ['eco-lodge', 'nghỉ dưỡng', 'sông', 'rừng', 'phong nha', 'national geographic'],
    tips: [
      'Đặt phòng trước ít nhất 2–4 tuần vào mùa hè',
      'Đây là điểm dừng hoàn hảo trước/sau khi khám phá các hang động Phong Nha',
      'Tắm sông dưới những tán cây rừng — trải nghiệm không thể tìm ở nơi khác',
    ],
    nearbyFood: ['Nhà hàng trong Chày Lập Ecolodge'],
    nearbyStay: ['Đây chính là điểm lưu trú', 'Phong Nha Farmstay (thay thế)'],
    images: ['chay-lap-1.jpg', 'chay-lap-2.jpg', 'chay-lap-3.jpg'],
  },
  {
    id: 41,
    name: 'Sông Son – Hành trình thuyền vào Phong Nha',
    nameEn: 'Son River Boat Journey',
    category: 'nature',
    subcategory: 'Sông & Hành trình thuyền',
    province: 'Quảng Trị',
    lat: 17.5600,
    lng: 106.2500,
    address: 'Xã Sơn Trạch, huyện Bố Trạch, tỉnh Quảng Trị',
    description: `Hành trình thuyền trên Sông Son từ bến Xuân Sơn vào Động Phong Nha dài khoảng 3km là một trong những hành trình thuyền đẹp nhất Việt Nam. Hai bên bờ là núi đá vôi dựng đứng phủ cây xanh, dòng sông xanh trong phản chiếu bầu trời và núi rừng. Buổi sáng sớm có sương mờ bảng lảng — cảnh như tranh thủy mặc.`,
    hours: '07:00 – 16:00 (theo giờ tàu vào Phong Nha)',
    admission: 'Bao gồm trong vé Động Phong Nha',
    phone: '',
    website: '',
    rating: 4.8,
    reviews: 4532,
    duration: '30–45 phút (mỗi chiều)',
    bestTime: 'Sáng sớm (6–9h) — sương mờ và nước trong nhất',
    highlight: false,
    tags: ['sông', 'thuyền', 'phong nha', 'cảnh đẹp', 'núi đá vôi'],
    tips: [
      'Chọn chỗ ngồi ngoài mũi thuyền để ngắm cảnh tốt nhất',
      'Mang kem chống nắng dù trời mát — ánh sáng phản chiếu từ mặt nước vẫn rát',
    ],
    nearbyFood: ['Phong Nha Farmstay', 'Nhà hàng bến thuyền'],
    nearbyStay: ['Chày Lập Ecolodge', 'Phong Nha Farmstay'],
    images: ['song-son-1.jpg', 'song-son-2.jpg'],
  },
  {
    id: 42,
    name: 'Bãi biển Nhân Trạch (Quán Hàu)',
    nameEn: 'Nhan Trach Beach',
    category: 'beach',
    subcategory: 'Bãi biển',
    province: 'Quảng Trị',
    lat: 17.3742,
    lng: 106.5811,
    address: 'Xã Nhân Trạch, huyện Bố Trạch, tỉnh Quảng Trị',
    description: `Bãi biển Nhân Trạch (còn gọi là biển Quán Hàu) là bãi tắm địa phương yêu thích của người dân vùng Bắc Quảng Trị, phía nam Đồng Hới. Bờ cát trắng sạch, sóng vừa, rừng phi lao xanh mát tạo không gian nghỉ ngơi dễ chịu. Nước biển trong, ít đá ngầm, phù hợp gia đình có trẻ nhỏ.`,
    hours: 'Mở cửa tự do',
    admission: 'Miễn phí',
    phone: '',
    website: '',
    rating: 4.1,
    reviews: 876,
    duration: 'Nửa ngày',
    bestTime: 'Tháng 5–8',
    highlight: false,
    tags: ['biển', 'gia đình', 'phi lao', 'tắm biển'],
    tips: [
      'Cách Đồng Hới ~20km về phía nam, thuận tiện trên đường về từ Quảng Trị',
    ],
    nearbyFood: ['Quán hải sản Nhân Trạch'],
    nearbyStay: ['Nhà nghỉ địa phương'],
    images: ['nhan-trach-1.jpg'],
  },
  {
    id: 43,
    name: 'Động Thiên Cung – Phong Nha (Tiên Sơn Cave)',
    nameEn: 'Tien Son Cave',
    category: 'nature',
    subcategory: 'Hang động',
    province: 'Quảng Trị',
    lat: 17.5533,
    lng: 106.2900,
    address: 'Xã Sơn Trạch, huyện Bố Trạch, tỉnh Quảng Trị',
    description: `Động Tiên Sơn (còn gọi Thiên Cung) nằm trên sườn núi cao 200m so với Sông Son, gần Động Phong Nha. Đây là hang khô với những măng đá, nhũ đá đẹp và nhiều nhạc đá nổi tiếng — gõ vào tạo ra âm thanh như nhạc cụ thực sự. Tuy nhỏ hơn Thiên Đường nhưng Tiên Sơn có nét đẹp thơ mộng riêng và dễ kết hợp khi thăm Phong Nha cùng ngày.`,
    hours: '07:30 – 16:30',
    admission: '80.000 VNĐ/người',
    phone: '0232 3677 021',
    website: '',
    rating: 4.4,
    reviews: 1654,
    duration: '45–60 phút',
    bestTime: 'Tháng 2–8',
    highlight: false,
    tags: ['hang động', 'nhũ đá', 'nhạc đá', 'phong nha'],
    tips: [
      'Mua combo vé Phong Nha + Tiên Sơn để tiết kiệm',
      'Leo ~150 bậc thang để vào hang — cần sức khỏe bình thường',
    ],
    nearbyFood: ['Nhà hàng bến thuyền Phong Nha'],
    nearbyStay: ['Phong Nha Farmstay', 'Chày Lập Ecolodge'],
    images: ['tien-son-1.jpg'],
  },
  {
    id: 44,
    name: 'Suối nước nóng Bang',
    nameEn: 'Bang Hot Spring',
    category: 'nature',
    subcategory: 'Suối nước nóng',
    province: 'Quảng Trị',
    lat: 17.6500,
    lng: 106.0500,
    address: 'Xã Lê Hóa, huyện Tuyên Hóa, tỉnh Quảng Trị',
    description: `Suối nước nóng Bang nằm ẩn sâu trong thung lũng Tuyên Hóa, với nhiệt độ nước 105°C — một trong những nguồn suối nước nóng có nhiệt độ cao nhất Việt Nam. Khu du lịch sinh thái bao quanh dòng suối nóng với bể ngâm nước khoáng, khung cảnh rừng núi yên tĩnh tuyệt đẹp. Nước khoáng được chứng minh có tác dụng chữa bệnh xương khớp, da liễu.`,
    hours: '07:00 – 20:00',
    admission: '50.000 – 120.000 VNĐ/người',
    phone: '0232 3877 234',
    website: '',
    rating: 4.3,
    reviews: 1087,
    duration: '2–4 giờ',
    bestTime: 'Tháng 10–3 (trời mát, ngâm suối thích nhất)',
    highlight: false,
    tags: ['suối nước nóng', 'khoáng chất', 'thư giãn', 'trị liệu'],
    tips: [
      'Nước trong bể pha loãng khoảng 40–42°C — không bao giờ ngâm thẳng vào nguồn 105°C',
      'Mang đồ bơi theo, thuê khăn tại chỗ',
      'Kết hợp tham quan huyện Tuyên Hóa và Minh Hóa nếu có thời gian',
    ],
    nearbyFood: ['Nhà hàng trong khu suối Bang', 'Quán ăn thị trấn Đồng Lê'],
    nearbyStay: ['Nhà nghỉ gần suối Bang', 'Homestay Tuyên Hóa'],
    images: ['suoi-bang-1.jpg'],
  },
];

// ============================================================
//  SERVICES — dịch vụ du lịch
// ============================================================
const services = {
  stays: [
    {
      id: 's1',
      name: 'Khách sạn Sài Gòn Đông Hà',
      type: 'Khách sạn 4 sao',
      lat: 16.8470,
      lng: 107.0988,
      address: '180 Lê Duẩn, TP. Đông Hà',
      phone: '0233 3560 999',
      website: 'saigonquangtri.vn',
      email: 'info@saigonquangtri.vn',
      priceRange: '800.000 – 2.500.000 VNĐ/đêm',
      hours: 'Check-in: 14:00 | Check-out: 12:00',
      rating: 4.5,
      amenities: ['WiFi', 'Hồ bơi', 'Nhà hàng', 'Bar', 'Gym', 'Spa'],
      description: 'Khách sạn cao cấp nhất Đông Hà, nằm trung tâm thành phố, thuận tiện tham quan các điểm du lịch.',
    },
    {
      id: 's2',
      name: 'Resort Cửa Tùng',
      type: 'Resort biển 3 sao',
      lat: 17.0265,
      lng: 107.1001,
      address: 'Bãi biển Cửa Tùng, huyện Vĩnh Linh',
      phone: '0233 3870 567',
      website: 'cuatungresort.vn',
      email: 'booking@cuatungresort.vn',
      priceRange: '600.000 – 1.800.000 VNĐ/đêm',
      hours: 'Check-in: 14:00 | Check-out: 12:00',
      rating: 4.3,
      amenities: ['WiFi', 'Bể bơi', 'Nhà hàng hải sản', 'Bãi biển riêng'],
      description: 'Resort ngay sát biển Cửa Tùng, lý tưởng để thư giãn và tắm biển.',
    },
    {
      id: 's3',
      name: 'Nhà khách La Vang',
      type: 'Nhà khách tôn giáo',
      lat: 16.7476,
      lng: 107.1198,
      address: 'Khu hành hương La Vang, huyện Hải Lăng',
      phone: '0233 3852 456',
      website: '',
      email: 'nkhachlavang@gmail.com',
      priceRange: '200.000 – 500.000 VNĐ/đêm',
      hours: 'Check-in: 13:00 | Check-out: 11:00',
      rating: 4.0,
      amenities: ['WiFi', 'Bãi đỗ xe rộng', 'Nhà ăn'],
      description: 'Nhà khách phục vụ khách hành hương, gần trung tâm linh địa La Vang.',
    },
    {
      id: 's4',
      name: 'Khách sạn Hòa Bình',
      type: 'Khách sạn 3 sao',
      lat: 16.7420,
      lng: 107.1885,
      address: 'Thị xã Quảng Trị',
      phone: '0233 3852 300',
      website: '',
      email: '',
      priceRange: '350.000 – 900.000 VNĐ/đêm',
      hours: 'Check-in: 14:00 | Check-out: 12:00',
      rating: 4.1,
      amenities: ['WiFi', 'Điều hòa', 'Quầy bar'],
      description: 'Gần Thành Cổ Quảng Trị, thuận tiện tham quan trung tâm thị xã.',
    },
  ],

  restaurants: [
    {
      id: 'r1',
      name: 'Nhà hàng Hải sản Cửa Việt',
      type: 'Nhà hàng hải sản',
      lat: 16.9290,
      lng: 107.1538,
      address: 'Bến cảng Cửa Việt, huyện Gio Linh',
      phone: '0905 123 456',
      priceRange: '200.000 – 800.000 VNĐ/người',
      hours: '10:00 – 22:00',
      rating: 4.6,
      specialties: ['Tôm hùm', 'Cua biển', 'Cá chim', 'Mực nang'],
      description: 'Hải sản tươi sống từ thuyền ngư dân, giá cả hợp lý, ngay cảng Cửa Việt.',
    },
    {
      id: 'r2',
      name: 'Quán Cháo Bột Lọc – Cô Lan',
      type: 'Quán ăn đặc sản',
      lat: 16.8455,
      lng: 107.0982,
      address: '45 Trần Phú, TP. Đông Hà',
      phone: '0905 234 567',
      priceRange: '30.000 – 80.000 VNĐ/người',
      hours: '06:00 – 14:00',
      rating: 4.7,
      specialties: ['Bột lọc', 'Bánh Nậm', 'Cơm hến', 'Bún Bò Huế'],
      description: 'Quán ăn sáng nổi tiếng Đông Hà với các món bột đặc sản miền Trung.',
    },
    {
      id: 'r3',
      name: 'Nhà hàng Sông Hiếu',
      type: 'Nhà hàng đặc sản địa phương',
      lat: 16.8502,
      lng: 107.1034,
      address: 'Bờ sông Hiếu, TP. Đông Hà',
      phone: '0233 3553 789',
      priceRange: '150.000 – 500.000 VNĐ/người',
      hours: '11:00 – 22:00',
      rating: 4.4,
      specialties: ['Tôm nướng', 'Bún chả', 'Vịt nướng Quảng Trị', 'Rượu cần'],
      description: 'Nhà hàng view sông Hiếu đẹp, thực đơn phong phú đặc sản Quảng Trị.',
    },
    {
      id: 'r4',
      name: 'Bánh mì Hải Phòng – Quảng Trị',
      type: 'Bánh mì & Đồ ăn vặt',
      lat: 16.7412,
      lng: 107.1879,
      address: 'Thị xã Quảng Trị',
      phone: '0905 345 678',
      priceRange: '15.000 – 35.000 VNĐ/ổ',
      hours: '06:00 – 10:00, 15:00 – 20:00',
      rating: 4.5,
      specialties: ['Bánh mì đặc biệt', 'Bánh mì thịt nguội'],
      description: 'Tiệm bánh mì nổi tiếng gần Thành Cổ, bánh giòn nhân phong phú.',
    },
  ],

  transport: [
    {
      id: 't1',
      name: 'Cho thuê xe máy Minh Tuấn',
      type: 'Cho thuê xe máy',
      lat: 16.8445,
      lng: 107.0970,
      address: '12 Lê Duẩn, TP. Đông Hà',
      phone: '0905 567 890',
      priceRange: '100.000 – 200.000 VNĐ/ngày',
      hours: '07:00 – 20:00',
      vehicles: ['Wave Alpha', 'Airblade', 'SH Mode', 'Exciter'],
      description: 'Cho thuê xe máy chất lượng, giá cả hợp lý, có giao xe tận nơi.',
    },
    {
      id: 't2',
      name: 'Taxi Sông Hiếu',
      type: 'Dịch vụ taxi',
      lat: 16.8450,
      lng: 107.0990,
      address: 'Toàn tỉnh Quảng Trị',
      phone: '0233 3567 890',
      priceRange: '12.000 – 15.000 VNĐ/km',
      hours: '24/7',
      description: 'Dịch vụ taxi an toàn, uy tín, phục vụ toàn tỉnh Quảng Trị.',
    },
    {
      id: 't3',
      name: 'Công ty TNHH Vận chuyển Du lịch Quảng Trị',
      type: 'Cho thuê xe ô tô có lái',
      lat: 16.8460,
      lng: 107.1000,
      address: '88 Hùng Vương, TP. Đông Hà',
      phone: '0905 678 901',
      email: 'booking@qlquangtri.vn',
      priceRange: '700.000 – 2.000.000 VNĐ/ngày',
      hours: '07:00 – 19:00',
      vehicles: ['4 chỗ', '7 chỗ', '16 chỗ', '35 chỗ'],
      description: 'Cho thuê xe có tài xế, tour chuyên nghiệp khắp Quảng Trị và các tỉnh lân cận.',
    },
    {
      id: 't4',
      name: 'Tàu cao tốc Cửa Việt – Cồn Cỏ',
      type: 'Tàu cao tốc',
      lat: 16.9285,
      lng: 107.1530,
      address: 'Bến tàu Cửa Việt, huyện Gio Linh',
      phone: '0233 3568 123',
      priceRange: '150.000 VNĐ/chiều',
      hours: 'Khởi hành: 07:00 và 13:00 hàng ngày',
      description: 'Tàu cao tốc duy nhất đến đảo Cồn Cỏ. Đặt vé trước qua điện thoại.',
    },
  ],

  guides: [
    {
      id: 'g1',
      name: 'Anh Nguyễn Văn Hùng',
      type: 'Hướng dẫn viên địa phương',
      lat: 16.8456,
      lng: 107.0994,
      phone: '0905 111 222',
      email: 'hvhung.guide@gmail.com',
      languages: ['Tiếng Việt', 'Tiếng Anh'],
      specialties: ['Di tích chiến tranh', 'Lịch sử Quảng Trị', 'Đường Trường Sơn'],
      priceRange: '500.000 – 1.000.000 VNĐ/ngày',
      rating: 4.9,
      experience: '15 năm',
      description: 'Hướng dẫn viên kỳ cựu, am hiểu sâu sắc lịch sử chiến tranh Quảng Trị. Đặt lịch trước ít nhất 2 ngày.',
    },
    {
      id: 'g2',
      name: 'Cô Lê Thị Mai',
      type: 'Hướng dẫn viên',
      lat: 16.7416,
      lng: 107.1891,
      phone: '0905 333 444',
      email: 'ltmai.guide@gmail.com',
      languages: ['Tiếng Việt', 'Tiếng Pháp', 'Tiếng Anh'],
      specialties: ['Linh địa La Vang', 'Văn hóa Quảng Trị', 'Lịch sử triều Nguyễn'],
      priceRange: '400.000 – 800.000 VNĐ/ngày',
      rating: 4.8,
      experience: '10 năm',
      description: 'Hướng dẫn viên chuyên mảng tâm linh và văn hóa, am hiểu La Vang và các di tích thời Nguyễn.',
    },
    {
      id: 'g3',
      name: 'Công ty Du lịch Quảng Trị Travel',
      type: 'Công ty tour',
      lat: 16.8462,
      lng: 107.1005,
      address: '55 Lê Duẩn, TP. Đông Hà',
      phone: '0233 3559 222',
      email: 'tour@quangtritravel.vn',
      website: 'quangtritravel.vn',
      priceRange: '300.000 – 1.500.000 VNĐ/người/ngày (tùy tour)',
      hours: '08:00 – 17:30 (T2–T7)',
      description: 'Công ty tour uy tín chuyên các tour Quảng Trị 1–5 ngày, tour DMZ, tour khám phá thiên nhiên.',
    },
  ],
};

// ============================================================
//  ITINERARY TEMPLATES — mẫu lộ trình tham quan
// ============================================================
const itineraryTemplates = {
  '1day-history': {
    title: '1 Ngày Khám Phá Lịch Sử Quảng Trị',
    description: 'Hành trình 1 ngày đầy ắp ký ức lịch sử từ chiến tranh đến thống nhất',
    schedule: [
      { time: '06:30', destId: 10, type: 'breakfast', note: 'Ăn sáng hải sản Cửa Tùng hoặc bún bò tại quán địa phương' },
      { time: '07:30', destId: 2, type: 'visit', duration: 90, note: 'Cầu Hiền Lương – Sông Bến Hải: tham quan đôi bờ chia cắt' },
      { time: '09:00', destId: 3, type: 'visit', duration: 120, note: 'Địa đạo Vịnh Mốc: đi bộ trong lòng đất, nghe chuyện kể' },
      { time: '11:30', type: 'lunch', note: 'Ăn trưa tại nhà hàng hải sản Cửa Tùng' },
      { time: '13:00', destId: 4, type: 'visit', duration: 90, note: 'Nghĩa trang Trường Sơn: viếng và tưởng niệm' },
      { time: '15:00', destId: 1, type: 'visit', duration: 90, note: 'Thành Cổ Quảng Trị: tham quan và chiêm nghiệm' },
      { time: '17:00', type: 'free', note: 'Dạo bộ thị xã Quảng Trị, mua đồ lưu niệm' },
      { time: '18:30', type: 'dinner', note: 'Ăn tối tại nhà hàng đặc sản Quảng Trị' },
    ],
  },
  '1day-nature': {
    title: '1 Ngày Khám Phá Thiên Nhiên & Biển',
    description: 'Hành trình biển, rừng và suối nước nóng',
    schedule: [
      { time: '06:00', type: 'breakfast', note: 'Ăn sáng sớm tại khách sạn' },
      { time: '07:00', destId: 11, type: 'visit', duration: 120, note: 'Biển Cửa Việt: tắm biển sáng sớm' },
      { time: '09:30', type: 'travel', note: 'Di chuyển vào Đakrông (1.5 giờ)' },
      { time: '11:00', destId: 8, type: 'visit', duration: 60, note: 'Rừng Đakrông: ngắm cảnh, đi bộ ngắn' },
      { time: '12:00', type: 'lunch', note: 'Ăn trưa đặc sản dân tộc Pa Kô' },
      { time: '13:30', destId: 9, type: 'visit', duration: 120, note: 'Suối nước nóng Đakrông: ngâm mình thư giãn' },
      { time: '16:00', type: 'travel', note: 'Quay về Đông Hà' },
      { time: '18:00', type: 'dinner', note: 'Ăn tối nhà hàng Sông Hiếu' },
    ],
  },
  '2day-comprehensive': {
    title: '2 Ngày Khám Phá Toàn Diện Quảng Trị',
    description: 'Hành trình cân bằng giữa lịch sử, thiên nhiên và biển cả',
    schedule: [
      // Ngày 1
      { time: '07:00', day: 1, destId: 2, type: 'visit', duration: 90, note: 'Cầu Hiền Lương' },
      { time: '09:00', day: 1, destId: 3, type: 'visit', duration: 120, note: 'Địa đạo Vịnh Mốc' },
      { time: '12:00', day: 1, type: 'lunch', note: 'Hải sản Cửa Tùng' },
      { time: '13:30', day: 1, destId: 10, type: 'visit', duration: 120, note: 'Biển Cửa Tùng: bơi và thư giãn' },
      { time: '16:00', day: 1, destId: 4, type: 'visit', duration: 90, note: 'Nghĩa trang Trường Sơn' },
      { time: '19:00', day: 1, type: 'dinner', note: 'Ăn tối Đông Hà — bún bò, bánh bèo' },
      // Ngày 2
      { time: '07:30', day: 2, destId: 1, type: 'visit', duration: 90, note: 'Thành Cổ Quảng Trị' },
      { time: '09:30', day: 2, destId: 13, type: 'visit', duration: 90, note: 'Linh địa La Vang' },
      { time: '11:30', day: 2, type: 'lunch', note: 'Cơm chay hoặc đặc sản gần La Vang' },
      { time: '13:30', day: 2, destId: 9, type: 'visit', duration: 120, note: 'Suối nước nóng Đakrông' },
      { time: '16:30', day: 2, type: 'free', note: 'Tự do mua sắm, tham quan Đông Hà' },
      { time: '19:00', day: 2, type: 'dinner', note: 'Ăn tối hải sản Cửa Việt' },
    ],
  },
  '3day-full': {
    title: '3 Ngày Trọn Vẹn Quảng Trị',
    description: 'Khám phá tất cả điểm nổi bật: lịch sử, biển, núi, đảo và tâm linh',
    schedule: [
      // Ngày 1: Vùng bắc (Vĩnh Linh)
      { time: '07:00', day: 1, destId: 2, type: 'visit', duration: 90, note: 'Cầu Hiền Lương – khởi đầu hành trình' },
      { time: '09:00', day: 1, destId: 3, type: 'visit', duration: 120, note: 'Địa đạo Vịnh Mốc' },
      { time: '12:00', day: 1, type: 'lunch', note: 'Hải sản Cửa Tùng' },
      { time: '14:00', day: 1, destId: 10, type: 'visit', duration: 180, note: 'Biển Cửa Tùng: tắm biển chiều' },
      { time: '19:00', day: 1, type: 'dinner', note: 'Tiệc hải sản tối' },
      // Ngày 2: Trung tâm (Đông Hà + Quảng Trị)
      { time: '07:30', day: 2, destId: 13, type: 'visit', duration: 90, note: 'Linh địa La Vang — hành hương tâm linh' },
      { time: '09:30', day: 2, destId: 1, type: 'visit', duration: 90, note: 'Thành Cổ Quảng Trị' },
      { time: '12:00', day: 2, type: 'lunch', note: 'Đặc sản Quảng Trị' },
      { time: '14:00', day: 2, destId: 4, type: 'visit', duration: 90, note: 'Nghĩa trang Trường Sơn' },
      { time: '16:30', day: 2, destId: 5, type: 'visit', duration: 60, note: 'Nghĩa trang Đường 9' },
      { time: '19:30', day: 2, type: 'dinner', note: 'Nhà hàng Sông Hiếu Đông Hà' },
      // Ngày 3: Đảo Cồn Cỏ hoặc Khe Sanh
      { time: '06:30', day: 3, type: 'travel', note: 'Ra cảng Cửa Việt' },
      { time: '07:00', day: 3, destId: 12, type: 'visit', duration: 360, note: 'Đảo Cồn Cỏ: lặn biển, ngắm san hô' },
      { time: '13:30', day: 3, type: 'lunch', note: 'Hải sản tươi trên đảo' },
      { time: '15:00', day: 3, type: 'travel', note: 'Tàu về Cửa Việt' },
      { time: '17:00', day: 3, type: 'free', note: 'Mua sắm đặc sản, chuẩn bị về' },
    ],
  },
};

// ============================================================
//  TRAVEL TIPS — mẹo du lịch tổng quát
// ============================================================
const generalTips = [
  {
    category: 'Thời tiết',
    icon: '🌤️',
    tips: [
      'Thời gian đẹp nhất: Tháng 3–5 (mùa xuân) và Tháng 9–11 (sau mùa mưa)',
      'Tháng 6–8: nóng nhưng biển đẹp nhất, thích hợp tắm biển',
      'Tháng 11–2: mùa mưa, có thể lạnh (15–20°C), không phù hợp biển',
      'Thánh địa La Vang đẹp nhất dịp Đại hội hành hương (tháng 8, năm lẻ)',
    ],
  },
  {
    category: 'Di chuyển',
    icon: '🚗',
    tips: [
      'Từ Hà Nội: tàu hỏa (8–9h) hoặc xe khách (10–12h); máy bay đến sân bay Đồng Hới (Quảng Trị) rồi thuê xe vào',
      'Từ Đà Nẵng/Huế: xe máy hoặc xe bus (2–3 giờ)',
      'Thuê xe máy tại Đông Hà: 100.000–150.000 VNĐ/ngày, tốt nhất để khám phá vùng quê',
      'Xe máy có thể đi hầu hết các điểm trong tỉnh; một số đường núi cần xe địa hình',
      'Grab/taxi có tại Đông Hà nhưng khan hiếm ở vùng ngoại ô',
    ],
  },
  {
    category: 'Ẩm thực',
    icon: '🍜',
    tips: [
      'Bún bò Quảng Trị – khác với Huế, ít sả hơn và thêm đặc sản địa phương',
      'Bánh ướt Quảng Trị – mỏng, mịn, ăn kèm thịt heo nướng',
      'Hải sản Cửa Việt và Cửa Tùng – tươi ngon, giá rẻ hơn Đà Nẵng 50%',
      'Cà phê Khe Sanh – đặc sản mua về làm quà, hương vị đặc trưng vùng cao',
      'Rượu cần dân tộc Pa Kô, Vân Kiều – thử ở vùng núi Đakrông/Hướng Hóa',
      'Mắm Cửa Tùng – mắm nêm ngon nổi tiếng cả nước',
    ],
  },
  {
    category: 'Lưu trú',
    icon: '🏨',
    tips: [
      'Đông Hà: trung tâm tỉnh, nhiều khách sạn từ budget đến 4 sao',
      'Thị xã Quảng Trị: gần Thành Cổ, yên tĩnh, phù hợp gia đình',
      'Vùng biển Cửa Tùng, Cửa Việt: resort, nhà nghỉ, homestay',
      'Khu núi Đakrông/Hướng Hóa: homestay dân tộc trải nghiệm văn hóa độc đáo',
      'Mùa hè nên đặt phòng trước 1–2 tuần, dịp lễ nên đặt trước 1 tháng',
    ],
  },
  {
    category: 'Lưu ý văn hóa',
    icon: '🙏',
    tips: [
      'Quảng Trị là vùng đất lịch sử đặc biệt — thể hiện sự tôn trọng tại các di tích, nghĩa trang',
      'Khi thăm nghĩa trang liệt sĩ: không ăn uống, không chụp ảnh tự sướng thiếu nghiêm trang',
      'Tại linh địa La Vang và chùa: mặc quần áo kín đáo, nói chuyện nhỏ nhẹ',
      'Người dân tộc Pa Kô, Vân Kiều có phong tục riêng — hỏi phép trước khi chụp ảnh',
    ],
  },
  {
    category: 'An toàn',
    icon: '⚠️',
    tips: [
      'Bom mìn chưa nổ (UXO) vẫn còn ở một số vùng rừng núi — KHÔNG tự ý đi lạc đường',
      'Mùa mưa lũ (tháng 9–11): kiểm tra dự báo thời tiết, tránh vùng ngập lụt',
      'Biển Quảng Trị có sóng mạnh — tắm đúng khu vực có cờ xanh và phao cứu sinh',
      'Đường núi đến Khe Sanh, Đakrông có nhiều khúc quanh — đi xe máy cẩn thận, không vượt ẩu',
    ],
  },
];

// ============================================================
//  QUANG TRI FACTS — thông tin tổng quát về Quảng Trị
// ============================================================
const REGIONS = {
  north:         { label: 'Miền Bắc',         icon: '🏔️' },
  'north-central':{ label: 'Bắc Trung Bộ',    icon: '🌊' },
  central:       { label: 'Trung Trung Bộ',    icon: '🏯' },
  'south-central':{ label: 'Nam Trung Bộ',     icon: '☀️' },
  highlands:     { label: 'Tây Nguyên',        icon: '🌲' },
  south:         { label: 'Miền Nam',          icon: '🌴' },
  islands:       { label: 'Hải Đảo',          icon: '🏝️' },
};

const provinceFacts = {
  name: 'Việt Nam',
  capital: 'Hà Nội',
  area: '331.212 km²',
  population: 'khoảng 100 triệu người',
  coordinates: { lat: 16.35, lng: 107.5 },
  defaultZoom: 6,
  description: 'Quảng Trị — vùng đất thiêng liêng nằm ở trung tâm miền Trung Việt Nam, nổi tiếng với những di tích lịch sử bi hùng của cuộc kháng chiến chống Mỹ. Nơi đây là nơi diễn ra những trận chiến ác liệt nhất và cũng là cầu nối lịch sử giữa hai miền Bắc – Nam. Ngày nay, Quảng Trị đang vươn lên mạnh mẽ với những bãi biển đẹp, vùng núi Trường Sơn hùng vĩ và nền văn hóa đa dạng của các dân tộc Pa Kô, Vân Kiều.',
  highlights: [
    '81 ngày đêm bảo vệ Thành Cổ Quảng Trị (1972)',
    'Ranh giới chia cắt đất nước tại sông Bến Hải (1954–1975)',
    'Địa đạo Vịnh Mốc — kỳ tích chiến tranh nhân dân',
    'Linh địa La Vang — hành hương Công giáo lớn nhất Đông Nam Á',
    'Bãi biển Cửa Tùng — "Nữ hoàng các bãi biển"',
    'Đảo Cồn Cỏ — thiên đường lặn biển hoang sơ',
  ],
};
